<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$partner=$block->getProfileDetail();
if (!empty($partner['shop_url'])) { ?>
    <?= $block->getChildHtml();?>
    <?php
} ?>
