<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$partner = $block->getProfileDetail();
$shopUrl = $escaper->escapeHtml($partner['shop_url']);
$sellerId = $partner->getSellerId();
$feeds = $block->getFeed();
if (empty($feeds['feed_price'])) {
    $feeds['feed_price'] = 0;
}
if (empty($feeds['feed_value'])) {
    $feeds['feed_value'] = 0;
}
if (empty($feeds['feed_quality'])) {
    $feeds['feed_quality'] = 0;
}
$widthPriceStar5 = $widthPriceStar4 = $widthPriceStar3 = $widthPriceStar2 = $widthPriceStar1 = 0;

$borderPriceStar5 = $borderPriceStar4 = $borderPriceStar3 = $borderPriceStar2 = $borderPriceStar1 = 0;

if ($feeds['feedcount']) {
    $widthPriceStar5 = ($feeds['price_star_5']*100)/$feeds['feedcount'];
    if ($widthPriceStar5) {
        $borderPriceStar5 = 3;
    }
    $widthPriceStar4 = ($feeds['price_star_4']*100)/$feeds['feedcount'];
    if ($widthPriceStar4) {
        $borderPriceStar4 = 3;
    }
    $widthPriceStar3 = ($feeds['price_star_3']*100)/$feeds['feedcount'];
    if ($widthPriceStar3) {
        $borderPriceStar3 = 3;
    }
    $widthPriceStar2 = ($feeds['price_star_2']*100)/$feeds['feedcount'];
    if ($widthPriceStar2) {
        $borderPriceStar2 = 3;
    }
    $widthPriceStar1 = ($feeds['price_star_1']*100)/$feeds['feedcount'];
    if ($widthPriceStar1) {
        $borderPriceStar1 = 3;
    }
}
$avgPriceRatingStar = round(($feeds['price']/20), 1, PHP_ROUND_HALF_UP);
$avgPriceRatingClass = "wk-mp-rating-icon wk-mp-star".(int)$avgPriceRatingStar;

$widthValueStar5 = $widthValueStar4 = $widthValueStar3 = $widthValueStar2 = $widthValueStar1 = 0;

$borderValueStar5 = $borderValueStar4 = $borderValueStar3 = $borderValueStar2 = $borderValueStar1 = 0;

if ($feeds['feedcount']) {
    $widthValueStar5 = ($feeds['value_star_5']*100)/$feeds['feedcount'];
    if ($widthValueStar5) {
        $borderValueStar5 = 3;
    }
    $widthValueStar4 = ($feeds['value_star_4']*100)/$feeds['feedcount'];
    if ($widthValueStar4) {
        $borderValueStar4 = 3;
    }
    $widthValueStar3 = ($feeds['value_star_3']*100)/$feeds['feedcount'];
    if ($widthValueStar3) {
        $borderValueStar3 = 3;
    }
    $widthValueStar2 = ($feeds['value_star_2']*100)/$feeds['feedcount'];
    if ($widthValueStar2) {
        $borderValueStar2 = 3;
    }
    $widthValueStar1 = ($feeds['value_star_1']*100)/$feeds['feedcount'];
    if ($widthValueStar1) {
        $borderValueStar1 = 3;
    }
}
$avgValueRatingStar = round(($feeds['value']/20), 1, PHP_ROUND_HALF_UP);
$avgValueRatingClass = "wk-mp-rating-icon wk-mp-star".(int)$avgValueRatingStar;

$widthQualityStar5 = $widthQualityStar4 = $widthQualityStar3 = $widthQualityStar2 = $widthQualityStar1 = 0;

$borderQualityStar5 = $borderQualityStar4 = $borderQualityStar3 = $borderQualityStar2 = $borderQualityStar1 = 0;

if ($feeds['feedcount']) {
    $widthQualityStar5 = ($feeds['quality_star_5']*100)/$feeds['feedcount'];
    if ($widthQualityStar5) {
        $borderQualityStar5 = 3;
    }
    $widthQualityStar4 = ($feeds['quality_star_4']*100)/$feeds['feedcount'];
    if ($widthQualityStar4) {
        $borderQualityStar4 = 3;
    }
    $widthQualityStar3 = ($feeds['quality_star_3']*100)/$feeds['feedcount'];
    if ($widthQualityStar3) {
        $borderQualityStar3 = 3;
    }
    $widthQualityStar2 = ($feeds['quality_star_2']*100)/$feeds['feedcount'];
    if ($widthQualityStar2) {
        $borderQualityStar2 = 3;
    }
    $widthQualityStar1 = ($feeds['quality_star_1']*100)/$feeds['feedcount'];
    if ($widthQualityStar1) {
        $borderQualityStar1 = 3;
    }
}
$avgQualityRatingStar = round(($feeds['quality']/20), 1, PHP_ROUND_HALF_UP);
$avgQualityRatingClass = "wk-mp-rating-icon wk-mp-star".(int)$avgQualityRatingStar;

$feedbackUrl = $helper->getRewriteUrl('marketplace/seller/feedback/shop/'.$shopUrl);

$totalRatingStar = $helper->getSelleRating($sellerId);
$ratingClass = "wk-mp-rating-icon wk-mp-star".(int)$totalRatingStar;
?>
<div class="wk-mp-rating-block" id="rating">
    <div class="wk-mp-rating-left">
        <div class="wk-mp-rating-avg">
            <div class="wk-mp-rating-avg-count <?= $escaper->escapeHtml($ratingClass)?>">
                <?= $escaper->escapeHtml($totalRatingStar); ?>
            </div>
            <div class="wk-mp-rating-avg-txt">
                <?= $escaper->escapeHtml(__('Average Rating (%1)', $feeds['feedcount']))?>
            </div>
            <div class="wk-mp-rating-avg-txt">
                <?php
                $review_percentage = (($totalRatingStar*100)/5);?>
                <?= /* @noEscape */ $review_percentage."% ".__('positive feedback');
                ?>
            </div>
            <div class="wk-mp-collection-view-btn">
                <a href="<?= $escaper->escapeUrl($feedbackUrl.'#customer-reviews')?>" 
                title="<?= $escaper->escapeHtml(__('Make a Review'))?>">
                    <?= $escaper->escapeHtml(__('Write your Review'))?>
                </a>
            </div>
        </div>
        <div class="wk-mp-rating-individual">
            <div class="wk-mp-rating-individual-left">
                <div class="<?= $escaper->escapeHtml($avgPriceRatingClass)?>">
                    <?= $escaper->escapeHtml($avgPriceRatingStar) ?>
                </div>
                <div class="wk-mp-rating-individual-txt">
                    <?= $escaper->escapeHtml(__('Average Price Rating (%1)', $feeds['feedcount']))?>
                </div>
            </div>
            <div class="wk-mp-rating-individual-right">
                <div  class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('5 Star (%1)', $feeds['price_star_5']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star5-rating-color-bar" 
                            style="width:<?= $escaper->escapeHtml($widthPriceStar5); ?>%; 
                            border-width:<?= $escaper->escapeHtml($borderPriceStar5); ?>px;"></span>
                        </small>
                    </div>
                </div>
                <div class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('4 Star (%1)', $feeds['price_star_4']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star4-rating-color-bar" 
                            style="width:<?= $escaper->escapeHtml($widthPriceStar4); ?>%; 
                            border-width:<?= $escaper->escapeHtml($borderPriceStar4); ?>px;"></span>
                        </small>
                    </div>
                </div>
                <div  class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('3 Star (%1)', $feeds['price_star_3']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star3-rating-color-bar"
                             style="width:<?= $escaper->escapeHtml($widthPriceStar3); ?>%;
                              border-width:<?= $escaper->escapeHtml($borderPriceStar3); ?>px;"></span>
                        </small>
                    </div>
                </div>
                <div class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('2 Star (%1)', $feeds['price_star_2']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star2-rating-color-bar"
                            style="width:<?= $escaper->escapeHtml($widthPriceStar2); ?>%; 
                            border-width:<?= $escaper->escapeHtml($borderPriceStar2); ?>px;"></span>
                        </small>
                    </div>
                </div>
                <div class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('1 Star (%1)', $feeds['price_star_1']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star1-rating-color-bar" 
                            style="width:<?= $escaper->escapeHtml($widthPriceStar1); ?>%; 
                            border-width:<?= $escaper->escapeHtml($borderPriceStar1); ?>px;"></span>
                        </small>
                    </div>
                </div>
            </div>
        </div>
        <div class="wk-mp-rating-individual">
            <div class="wk-mp-rating-individual-left">
                <div class="<?= $escaper->escapeHtml($avgValueRatingClass)?>">
                    <?= $escaper->escapeHtml($avgValueRatingStar) ?>
                </div>
                <div class="wk-mp-rating-individual-txt">
                    <?= $escaper->escapeHtml(__('Average Value Rating (%1)', $feeds['feedcount']))?>
                </div>
            </div>
            <div class="wk-mp-rating-individual-right">
                <div  class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('5 Star (%1)', $feeds['value_star_5']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star5-rating-color-bar"
                             style="width:<?= $escaper->escapeHtml($widthValueStar5); ?>%; 
                             border-width:<?= $escaper->escapeHtml($borderValueStar5); ?>px;"></span>
                        </small>
                    </div>
                </div>
                <div class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('4 Star (%1)', $feeds['value_star_4']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star4-rating-color-bar" 
                            style="width:<?= $escaper->escapeHtml($widthValueStar4); ?>%;
                             border-width:<?= $escaper->escapeHtml($borderValueStar4); ?>px;"></span>
                        </small>
                    </div>
                </div>
                <div  class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('3 Star (%1)', $feeds['value_star_3']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star3-rating-color-bar"
                             style="width:<?= $escaper->escapeHtml($widthValueStar3); ?>%;
                              border-width:<?= $escaper->escapeHtml($borderValueStar3); ?>px;"></span>
                        </small>
                    </div>
                </div>
                <div class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('2 Star (%1)', $feeds['value_star_2']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star2-rating-color-bar"
                            style="width:<?= $escaper->escapeHtml($widthValueStar2); ?>%; 
                            border-width:<?= $escaper->escapeHtml($borderValueStar2); ?>px;"></span>
                        </small>
                    </div>
                </div>
                <div class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('1 Star (%1)', $feeds['value_star_1']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star1-rating-color-bar"
                             style="width:<?= $escaper->escapeHtml($widthValueStar1); ?>%;
                              border-width:<?= $escaper->escapeHtml($borderValueStar1); ?>px;"></span>
                        </small>
                    </div>
                </div>
            </div>
        </div>
        <div class="wk-mp-rating-individual">
            <div class="wk-mp-rating-individual-left">
                <div class="<?= $escaper->escapeHtml($avgQualityRatingClass)?>">
                    <?= $escaper->escapeHtml($avgQualityRatingStar) ?>
                </div>
                <div class="wk-mp-rating-individual-txt">
                    <?= $escaper->escapeHtml(__('Average Quality Rating (%1)', $feeds['feedcount']))?>
                </div>
            </div>
            <div class="wk-mp-rating-individual-right">
                <div  class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('5 Star (%1)', $feeds['quality_star_5']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star5-rating-color-bar"
                             style="width:<?= $escaper->escapeHtml($widthQualityStar5); ?>%; 
                             border-width:<?= $escaper->escapeHtml($borderQualityStar5); ?>px;"></span>
                        </small>
                    </div>
                </div>
                <div class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('4 Star (%1)', $feeds['quality_star_4']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star4-rating-color-bar" 
                            style="width:<?= $escaper->escapeHtml($widthQualityStar4); ?>%; 
                            border-width:<?= $escaper->escapeHtml($borderQualityStar4); ?>px;"></span>
                        </small>
                    </div>
                </div>
                <div  class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('3 Star (%1)', $feeds['quality_star_3']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star3-rating-color-bar" 
                            style="width:<?= $escaper->escapeHtml($widthQualityStar3); ?>%; 
                            border-width:<?= $escaper->escapeHtml($borderQualityStar3); ?>px;"></span>
                        </small>
                    </div>
                </div>
                <div class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('2 Star (%1)', $feeds['quality_star_2']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star2-rating-color-bar"
                            style="width:<?= $escaper->escapeHtml($widthQualityStar2); ?>%; 
                            border-width:<?= $escaper->escapeHtml($borderQualityStar2); ?>px;"></span>
                        </small>
                    </div>
                </div>
                <div class="wk-mp-rating-progress-bar-container">
                    <div class="wk-mp-rating-individual-right-txt">
                        <?= $escaper->escapeHtml(__('1 Star (%1)', $feeds['quality_star_1']))?>
                    </div>
                    <div class="wk-mp-rating-individual-progress-bar">
                        <small>
                            <span class="wk-mp-rating-progress-color-bar wk-mp-star1-rating-color-bar"
                             style="width:<?= $escaper->escapeHtml($widthQualityStar1); ?>%; 
                             border-width:<?= $escaper->escapeHtml($borderQualityStar1); ?>px;"></span>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="wk-mp-rating-right">
        <?php
        foreach ($block->getFeedCollection() as $keyed) {
            $feedcustomer = $block->getCustomer($keyed['buyer_id']);
            $name = $keyed['feed_nickname'];
            $feedDateTime= strtotime($keyed['created_at']);
            $feedDate = date('M d, Y', $feedDateTime);
            $feedPrice = round(($keyed['feed_price']/20), 1, PHP_ROUND_HALF_UP);
            $feedValue = round(($keyed['feed_value']/20), 1, PHP_ROUND_HALF_UP);
            $feedQuality = round(($keyed['feed_quality']/20), 1, PHP_ROUND_HALF_UP);
            ?>
            <div class="wk-mp-rating-row">
                <div class="wk-mp-rating-customer-row">
                    <span class="wk-mp-rating-val-txt wk-mp-float-left">
                        <?= $escaper->escapeHtml($keyed['feed_summary'])?>
                    </span>
                    <span class="wk-mp-float-right">
                        <?= $escaper->escapeHtml(__("By %1 ", $name))?>
                        <i><?= $escaper->escapeHtml($feedDate)?></i>
                    </span>
                </div>
                <div class="wk-mp-rating-summary-container">
                    <div class="wk-mp-rating-review-row">
                        <span class="wk-mp-rating-txt">
                            <?= $escaper->escapeHtml(__("Rating")); ?>
                        </span>
                        <span class="wk-mp-rating-val">
                            <span class="wk-mp-rating-val-txt">
                                <?= $escaper->escapeHtml(__("Pricing")); ?>
                            </span>
                            <span class="wk-mp-rating-icon wk-mp-star<?= /* @noEscape */ $feedPrice?>">
                                <?= $escaper->escapeHtml($feedPrice)?>
                            </span>
                        </span>
                        <span class="wk-mp-rating-val">
                            <span class="wk-mp-rating-val-txt">
                                <?= $escaper->escapeHtml(__("Value")); ?>
                            </span>
                            <span class="wk-mp-rating-icon wk-mp-star<?= $escaper->escapeHtml($feedValue)?>">
                                <?= $escaper->escapeHtml($feedValue)?>
                            </span>
                        </span>
                        <span class="wk-mp-rating-val">
                            <span class="wk-mp-rating-val-txt">
                                <?= $escaper->escapeHtml(__("Quality")); ?>
                            </span>
                            <span class="wk-mp-rating-icon wk-mp-star<?= $escaper->escapeHtml($feedQuality)?>">
                                <?= $escaper->escapeHtml($feedQuality)?>
                            </span>
                        </span>
                    </div>
                    <p><?= $escaper->escapeHtml($keyed['feed_review'])?></p>
                </div>
            </div>
            <?php
        } ?>
        <div class="wk-mp-collection-view-btn">
            <a href="<?= $escaper->escapeUrl($feedbackUrl)?>" 
            title="<?= $escaper->escapeHtml(__('View All Reviews'))?>" target="_blank">
                <?= $escaper->escapeHtml(__('View All Reviews'))?>
            </a>
        </div>
    </div>
</div>
