<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$partner = $block->getProfileDetail();
$shopUrl = $escaper->escapeHtml($partner['shop_url']);
$sellerId = $partner->getSellerId();
$sellerProductCount = $helper->getSellerProCount($sellerId);
?>
<?php $products = $block->getBestsellProducts(); ?>
<?php if (count($products)) { ?>
    <div class="wk-mp-profile-block wk-mp-products-recently-added">
        <div class="block block-account">
            <div class="block-title">
                <strong><span><h4><?= $escaper->escapeHtml(__("Recently Added Products")) ?></h4></span></strong>
            </div>
        </div>
        <?php
        $products = $block->getBestsellProducts();
        $_helper = $viewModel->getCatalogHelperOutput();
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        ?>
        <div class="page-products page-with-filter fieldset wk-mp-fieldset" 
        <?php if ($products->count()): ?> <?= 'style="padding: 0;"';?> <?php endif; ?>>
            <?php
            $_helper = $viewModel->getCatalogHelperOutput();
            ?>
            <div class="products wrapper grid products-grid">
                <?php $iterator = 1; ?>
                <ol class="products list items product-items">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($products as $_product): ?>
                        <?= /* @escapeNotVerified */($iterator++ == 1)
                        ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                        <div class="product-item-info" data-container="product-grid">
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            ?>
                            <?php // Product Image ?>
                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                             class="product photo product-item-photo" tabindex="-1">
                                <?= $productImage->toHtml(); ?>
                            </a>
                            <div class="product details product-item-details">
                                <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                    href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                        <?= /* @noEscape */
                                        $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                <?php
                                $pos = $block->getPositioned() ? $block->getPositioned() :'';
                                $viewMode = 'grid';?>
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?=
                                    $escaper->escapeHtml(strpos($pos, $viewMode . '-actions') ? $position : ''); ?>>
                                        <div class="actions-primary"<?=
                                        $escaper->escapeHtml(strpos($pos, $viewMode . '-primary') ? $position : ''); ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                
                                                 <form data-role="tocart-form"
                                                    action="<?=
                                                                $escaper->escapeHtml(
                                                                    $viewModel->getCatalogHelperProductCompare()
                                                                    ->getAddToCartUrl($_product)
                                                                ) ?>"
                                                    method="post">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit" class="action tocart primary">
                                                        <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?=
                                                        $escaper->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span>
                                                        <?= $escaper->escapeHtml(__('Out of stock')) ?>
                                                    </span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary"
                                        <?= /* @noEscape */ strpos($pos, $viewMode . '-secondary')
                                        ? $position : ''; ?>>
                                            <?php if ($viewModel->getWishlistHelper()->isAllow()): ?>
                                                <a href="#"
                                                class="action towishlist"
                                                title="<?= $escaper->escapeHtml(__('Add to Wish List')); ?>"
                                                aria-label="<?= $escaper
                                                ->escapeHtml(__('Add to Wish List')); ?>"
                                                data-post='<?= /* @noEscape */ $block
                                                ->getAddToWishlistParams($_product); ?>'
                                                data-action="add-to-wishlist"
                                                role="button">
                                                    <span>
                                                        <?= $escaper->escapeHtml(__('Add to Wish List')) ?>
                                                    </span>
                                                </a>
                                            <?php endif; ?>
                                            <?php
                                            $compareHelper = $viewModel->getCatalogHelperProductCompare();
                                            ?>
                                            <a href="#"
                                            class="action tocompare"
                                            title="<?= $escaper->escapeHtml(__('Add to Compare')); ?>"
                                            aria-label="<?= $escaper->escapeHtml(__('Add to Compare')); ?>"
                                            data-post='<?= /* @noEscape */
                                                $compareHelper->getPostDataParams($_product); ?>'
                                            role="button">
                                                <span>
                                                    <?= $escaper->escapeHtml(__('Add to Compare')) ?></span>
                                            </a>
                                        </div>
                                    </div>
                                   
                                </div>
                            </div>
                        </div>
                        <?= ($iterator == count($products)+1) ? '</li>' : '' ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
        <div class="wk-mp-collection-view-btn">
            <a href="<?= $escaper->escapeUrl($helper
            ->getRewriteUrl('marketplace/seller/collection/shop/'.$shopUrl));?>" 
            title="<?= $escaper->escapeHtml(__('View Collection'))?>">
                <?= $escaper->escapeHtml(__('View All %1 Products', $sellerProductCount))?>
            </a>
        </div>
    </div>
<?php } ?>
<?= $block->getChildHtml()?>
