<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$shipmentData = $block->getShipmentData();
?>
<table class="email-items">
    <thead>
        <tr>
            <th class="item-info"><?= $escaper->escapeHtml(__("Items"));?></th>
            <th class="item-info"><?= $escaper->escapeHtml(__("Sku"));?></th>
            <th class="item-qty"><?= $escaper->escapeHtml(__("Qty"));?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($shipmentData["items"] as $item) { ?>
            <tr>
                <td class='item-info'><?= /* @noEscape */ $item["productName"]; ?></td>
                <td class='item-info'><?= $escaper->escapeHtml($item["sku"]); ?></td>
                <td class='item-qty'><?= $escaper->escapeHtml($item["qty"]); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>