<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
use Webkul\Marketplace\Model\Product;

$order = $block->getOrder();
$items = $block->getItems();
$itemsQtyToInvoice = $block->getInvoiceItemsQty();
$invoice = $block->getInvoice();
$paymentCode = '';
$colSpan = 9;
if ($order->getPayment()) {
    $colSpan = 10;
    $paymentCode = $order->getPayment()->getMethod();
}
?>
<div class="table-wrapper order-items">
    <table class="data table table-order-items" id="my-orders-table" 
    summary="<?= $escaper->escapeHtml(__('Items Invoiced')) ?>">
        <caption class="table-caption"><?= $escaper->escapeHtml(__('Items Invoiced')) ?></caption>
        <thead>
            <?php if ($block->isPagerDisplayed()): ?>
                <tr>
                    <td colspan="<?= $escaper->escapeHtml($colSpan) ?>"
                     data-block="order-items-pager-top" 
                     class="order-pager-wrapper order-pager-wrapper-top">
                        <?= $block->getPagerHtml() ?>
                    </td>
                </tr>
            <?php endif ?>
            <tr>
                <th class="col name"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                <th class="col price"><?= $escaper->escapeHtml(__('Price')) ?></th>
                <th class="col qty"><?= $escaper->escapeHtml(__('Qty')) ?></th>
                <th class="col price"><?= $escaper->escapeHtml(__('Subtotal')) ?></th>
                <?php
                if ($paymentCode == 'mpcashondelivery') {?>
                    <th class="col price"><?= $escaper->escapeHtml(__('COD Charges')) ?></th>
                    <?php
                } ?>
                <th class="col price"><?= $escaper->escapeHtml(__('Tax Total')) ?></th>
                <th class="col price"><?= $escaper->escapeHtml(__('Discount Total')) ?></th>
                <th class="col price"><?= $escaper->escapeHtml(__('Row Total')) ?></th>
                <th class="col price"><?= $escaper->escapeHtml(__('Admin Commission')) ?></th>
                <th class="col price"><?= $escaper->escapeHtml(__('Vendor Total')) ?></th>
            </tr>
        </thead>
        <?php
        $count = count($items);
        foreach ($items as $item) {
            if ($item->getParentItem()) {
                continue;
            }

            $invoicedQty = $itemsQtyToInvoice[$item->getItemId()];
            $orderedQty = $item->getQtyOrdered();
            $codchargesPerItem = 0;
            $rowTotal = $item->getMageproPrice() * $invoicedQty;
            $currencyRate = $item->getCurrencyRate();
            $totalTaxPerItem = ($item->getTotalTax() / $orderedQty) * $invoicedQty;
            $couponAmount = ($item->getAppliedCouponAmount() / $orderedQty) * $invoicedQty;
            $sellerItemCost= ($item->getActualSellerAmount() / $orderedQty) * $invoicedQty;
            $sellerItemCommission = ($item->getTotalCommission() / $orderedQty) * $invoicedQty;


            $result = [];
            if ($options = $item->getProductOptions()) {
                $result = $block->getItemOptionData($options, $result);
            }
            // for bundle product
            $bundleitems = $block->getMergedItems($item);
            $count = count($bundleitems);
            $index = 0;
            $prevOptionId = '';
            ?>
            <tbody>
                <?php
                if ($item->getProductType() != Product::PRODUCT_TYPE_BUNDLE) { ?>
                    <tr class="border" id="order-item-row-<?= $escaper->escapeHtml($item->getId()) ?>">
                        <?php
                        if ($item->getProductType()=='downloadable') { ?>
                            <td class="col name" data-th="<?= $escaper->escapeHtml(__('Product Name')); ?>">
                                <strong class="product name product-item-name">
                                    <?= $escaper->escapeHtml($item->getName()) ?></strong>
                                <?php if ($options = $block->getItemOptions($item)): ?>
                                    <dl class="item-options links">
                                        <?php foreach ($options as $option): ?>
                                            <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                                            <?php if (!$block->getPrintStatus()): ?>
                                                <?php $formatedOptionValue = $block
                                                ->getFormatedOptionValue($option) ?>
                                                <dd>
                                                    <?php if (isset($formatedOptionValue['full_view'])): ?>
                                                        <?= /* @noEscape */ $formatedOptionValue['full_view'] ?>
                                                    <?php else: ?>
                                                        <?= /* @noEscape */ $formatedOptionValue['value'] ?>
                                                    <?php endif; ?>
                                                </dd>
                                            <?php else: ?>
                                                <dd><?= $escaper->escapeHtml((isset($option['print_value'])
                                                 ? $option['print_value'] : $option['value'])) ?></dd>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </dl>
                                <?php endif; ?>
                                <?php /* downloadable */?>
                                <?php if ($links = $block->getDownloadableLinks($item->getId())): ?>
                                    <dl class="item-options links">
                                        <dt><?= /* @escapeNotVerified */
                                        $escaper->escapeHtml($block->getLinksTitle($item->getId())) ?></dt>
                                        <?php foreach ($links->getPurchasedItems() as $link): ?>
                                            <dd><?= $escaper->escapeHtml($link->getLinkTitle()); ?></dd>
                                        <?php endforeach; ?>
                                    </dl>
                                <?php endif; ?>
                                <?php /* EOF downloadable */?>

                                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                                <?php if ($addInfoBlock):?>
                                    <?= $addInfoBlock->setItem($item->getOrderItem())->toHtml(); ?>
                                <?php endif; ?>
                                <?= $escaper->escapeHtml($item->getDescription()) ?>
                                <?php $addInfoBlock = $block->getOrderItemAdditionalInfoBlock(); ?>
                                <?php if ($addInfoBlock): ?>
                                    <?= $addInfoBlock->setItem($item)->toHtml() ?>
                                <?php endif;?>
                            </td>
                            <?php
                        } else { ?>
                            <td class="col name" data-th="<?= $escaper->escapeHtml(__('Product Name')); ?>">
                                <strong class="product name product-item-name">
                                    <?= $escaper->escapeHtml($item->getName()) ?>
                                </strong>
                                <?php if ($options = $result): ?>
                                    <dl class="item-options">
                                    <?php foreach ($options as $option): ?>
                                        <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                                        <?php if (!$block->getPrintStatus()): ?>
                                            <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                                            <dd>
                                                <?php if (isset($formatedOptionValue['full_view'])): ?>
                                                    <?= /* @noEscape */ $formatedOptionValue['full_view'] ?>
                                                <?php else: ?>
                                                    <?= /* @noEscape */ $formatedOptionValue['value'] ?>
                                                <?php endif; ?>
                                            </dd>
                                        <?php else: ?>
                                            <dd>
                                                <?= /* @noEscape */ nl2br($escaper
                                                ->escapeHtml((isset($option['print_value'])
                                                 ? $option['print_value'] : $option['value']))) ?>
                                            </dd>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                    </dl>
                                <?php endif; ?>
                                <?php $addInfoBlock = $block->getOrderItemAdditionalInfoBlock(); ?>
                                <?php if ($addInfoBlock): ?>
                                    <?= $addInfoBlock->setItem($item)->toHtml() ?>
                                <?php endif;?>
                            </td>
                        <?php }?>
                        <td class="col price" data-th="<?= $escaper->escapeHtml(__('Price')); ?>">
                            <span class="price-excluding-tax" 
                            data-label="<?= $escaper->escapeHtml(__('Excl. Tax')); ?>">
                                <span class="cart-price">
                                    <?= /* @noEscape */ $order->formatPrice($item->getPrice()); ?>
                                </span>
                            </span>
                        </td>
                        <td class="col qty" data-th="<?= $escaper->escapeHtml(__('Qty')); ?>">
                            <?= $escaper->escapeHtml($item->getQty()*1) ?>
                        </td>
                        <td class="col price" data-th="<?= $escaper->escapeHtml(__('Subtotal')); ?>">
                        <?= /* @noEscape */ $order->formatPrice($block
                        ->getOrderedPricebyorder($currencyRate, $rowTotal));?></td>
                        <?php
                        if ($paymentCode == 'mpcashondelivery') {
                            $codchargesPerItem = ($item->getCodCharges() / $orderedQty) * $invoicedQty;
                            ?>
                            <td class="col price" data-th="<?= $escaper->escapeHtml(__('COD Charges')) ?>">
                            <?= /* @noEscape */ $order->formatPrice($block
                            ->getOrderedPricebyorder($currencyRate, $codchargesPerItem));?></td>
                            <?php
                        } ?>
                        <td class="col price" data-th="<?= $escaper->escapeHtml(__('Tax Total')); ?>">
                            <?= /* @noEscape */ $order->formatPrice(
                                $block->getOrderedPricebyorder($currencyRate, $totalTaxPerItem)
                            );?>
                        </td>
                        <td class="col price" data-th="<?= $escaper->escapeHtml(__('Discount Total')); ?>">
                            <?= /* @noEscape */ $order->formatPrice($block
                            ->getOrderedPricebyorder($currencyRate, $couponAmount));?></td>
                        <td class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Row Total')); ?>">
                        <?= /* @noEscape */ $order->formatPrice($block
                        ->getOrderedPricebyorder($currencyRate, $rowTotal));?></td>
                        <td class="col price" data-th="<?= $escaper->escapeHtml(__('Admin Commission')); ?>">
                        <?= /* @noEscape */ $order->formatPrice($block
                        ->getOrderedPricebyorder($currencyRate, $sellerItemCommission));?></td>
                        <td class="col price" data-th="<?= $escaper->escapeHtml(__('Vendor Total')); ?>">
                        <?= /* @noEscape */ $order->formatPrice($block
                        ->getOrderedPricebyorder($currencyRate, $sellerItemCost));?></td>
                    </tr>
                    <?php
                } else { ?>
                    <?php foreach ($bundleitems as $bundleitem): ?>
                        <?php
                        $bundleItemTotals = $block->getSellerOrdersList(
                            $order->getId(),
                            $bundleitem->getProductId(),
                            $bundleitem->getId()
                        );
                        $codCharges = 0;
                        foreach ($bundleItemTotals as $bundleItemTotal) {
                            $invoicedQty = $bundleitem->getQty();
                            $orderedQty = $bundleitem->getQtyOrdered();
                            $rowTotal = $bundleItemTotal->getMageproPrice() * $invoicedQty;
                            $currencyRate = $bundleItemTotal->getCurrencyRate();
                            $totalTaxPerItem = (
                                $bundleItemTotal->getTotalTax() / $orderedQty
                            ) * $invoicedQty;
                            $couponAmount = (
                                $bundleItemTotal->getAppliedCouponAmount() / $orderedQty
                            ) * $invoicedQty;
                            $sellerItemCost = (
                                $bundleItemTotal->getActualSellerAmount() / $orderedQty
                            ) * $invoicedQty;
                            $sellerItemCommission = (
                                $bundleItemTotal->getTotalCommission()/ $orderedQty
                            ) * $invoicedQty;
                            if ($paymentCode == 'mpcashondelivery') {
                                $codCharges = $bundleItemTotal->getCodCharges();
                            }
                        }
                        ?>
                        <?php $attributes_option = $block->getSelectionAttribute($bundleitem); ?>
                        <?php if ($bundleitem->getParentItem()): ?>
                            <?php $attributes = $attributes_option ?>
                            <?php if ($prevOptionId != $attributes['option_id']): ?>
                            <tr class="options-label">
                                <td class="col label" colspan="<?= /* @noEscape */ $colSpan ?>"
                                    data-th="<?= $escaper->escapeHtml(__('Product Name')); ?>">
                                    <?= $escaper->escapeHtml($attributes['option_label']) ?>
                                </td>
                            </tr>
                                <?php $prevOptionId = $attributes['option_id'] ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <tr<?= (++$index==$count)?' class="border bundle"':' class="bundle"' ?> 
                            id="order-item-row-<?= $escaper->escapeHtml($bundleitem->getId()) ?>">
                            <?php
                            if (!$bundleitem->getParentItem()) {?>
                                <td><h3 class="product-name">
                                    <?= $escaper->escapeHtml($bundleitem->getName()) ?></h3></td>
                                <td class="col price" data-rwd-label="<?= $escaper->escapeHtml(__('Price')) ?>">
                                    <span class="price-excluding-tax" 
                                    data-label="<?= $escaper->escapeHtml(__('Excl. Tax')); ?>">
                                        <?= /* @noEscape */ $order->formatPrice($item->getPrice());?>
                                    </span>
                                </td>
                                <td class="col qty item_status" 
                                data-rwd-label="<?= $escaper->escapeHtml(__('Status')) ?>">
                                    <ul class="items-qty">
                                        <?php if ($item->getQtyOrdered() > 0): ?>
                                            <li class="item">
                                                <span class="title">
                                                    <?= $escaper->escapeHtml(__('Ordered')); ?>
                                                </span>
                                                <span class="content">
                                                    <?= $escaper->escapeHtml($item->getQtyOrdered()*1) ?></span>
                                            </li>
                                        <?php endif; ?>
                                    </ul>
                                </td>
                                <td class="lin-hide">&nbsp;</td>
                                <td class="lin-hide">&nbsp;</td>
                                <td class="lin-hide">&nbsp;</td>
                                <td class="lin-hide">&nbsp;</td>
                                <td class="lin-hide">&nbsp;</td>
                                <td class="lin-hide">&nbsp;</td>
                                <?php
                            } else { ?>
                                <?php
                                ?>
                                <td class="col value" data-th="<?= $escaper->escapeHtml(__('Product Name')); ?>">
                                    <?= $block->getValueHtml($bundleitem)?>
                                    <?php $addInfoBlock = $block->getOrderItemAdditionalInfoBlock(); ?>
                                    <?php if ($addInfoBlock): ?>
                                        <?= $addInfoBlock->setItem($bundleitem)->toHtml() ?>
                                    <?php endif;?>
                                </td>
                                <td class="col price" data-rwd-label="<?= $escaper->escapeHtml(__('Price')) ?>">
                                <?= /* @noEscape */ $order->formatPrice($bundleitem->getPrice());?></td>
                                <td class="col qty item_status" 
                                data-rwd-label="<?= $escaper->escapeHtml(__('Qty')) ?>">
                                    <?= $escaper->escapeHtml($bundleitem->getQty()*1) ?>
                                </td>
                                <td class="col price" data-th="<?= $escaper->escapeHtml(__('Subtotal')); ?>">
                                <?= /* @noEscape */ $order->formatPrice($block
                                ->getOrderedPricebyorder($currencyRate, $rowTotal));?></td>
                                <?php if ($paymentCode == 'mpcashondelivery') { ?>
                                    <td class="col price" data-th="<?= $escaper->escapeHtml(__('COD Charges')) ?>">
                                    <?= /* @noEscape */ $order->formatPrice($block
                                    ->getOrderedPricebyorder($currencyRate, $codCharges));?></td>
                                    <?php
                                } ?>
                                <td class="col price" data-th="<?= $escaper->escapeHtml(__('Tax Total')); ?>">
                                    <?= /* @noEscape */ $order->formatPrice(
                                        $block->getOrderedPricebyorder($currencyRate, $totalTaxPerItem)
                                    );?>
                                </td>
                                <td class="col price" data-th="<?= $escaper->escapeHtml(__('Discount Total')); ?>">
                                    <?= /* @noEscape */ $order->formatPrice($block
                                    ->getOrderedPricebyorder($currencyRate, $couponAmount));?></td>
                                <td class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Row Total')); ?>">
                                <?= /* @noEscape */ $order->formatPrice($block
                                ->getOrderedPricebyorder($currencyRate, $rowTotal));?></td>
                                <td class="col price" data-th="<?= $escaper->escapeHtml(__('Admin Commission')); ?>">
                                <?= /* @noEscape */ $order->formatPrice($block
                                ->getOrderedPricebyorder($currencyRate, $sellerItemCommission));?></td>
                                <td class="col price" data-th="<?= $escaper->escapeHtml(__('Vendor Total')); ?>">
                                <?= /* @noEscape */ $order->formatPrice($block
                                ->getOrderedPricebyorder($currencyRate, $sellerItemCost));?></td>
                                <?php
                            }?>
                        </tr>
                    <?php endforeach; ?>
                    <?php
                }?>
            </tbody>
            <?php
        } ?>
        <tfoot>
            <?php if ($block->isPagerDisplayed()): ?>
                <tr>
                    <td colspan="<?= /* @noEscape */ $colSpan ?>"
                     data-block="order-items-pager-bottom"
                     class="order-pager-wrapper order-pager-wrapper-bottom">
                        <?= $block->getPagerHtml() ?>
                    </td>
                </tr>
            <?php endif ?>
            <?= $block->getChildHtml('marketplace_order_invoice_totals') ?>
        </tfoot>
    </table>
</div>
