<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Walletsystem
 * @author    Webkul
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

?>
<?php
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$isEnabled = $helper->getWalletenabled();
$magentoCurrentUrl = $block->getCurrentUrl();
?>
<?php
if ($isEnabled) { ?>
    <li
    class="walletsystemnav nav item <?= $escaper->escapeHtml(strpos($magentoCurrentUrl, 'walletsystem')
        !== false ? "current":"");?>">
        <?php if (strpos($magentoCurrentUrl, 'walletsystem') !== false) { ?>
            <strong><?=$escaper->escapeHtml(__('My Wallet')) ?></strong>
            <?php
        } else { ?>
            <a href="#"><?=$escaper->escapeHtml(__('My Wallet')) ?></a>
        <?php } ?>
        <ul class="nav items">
            <li 
            class="nav item <?= $escaper->escapeHtml(strpos($magentoCurrentUrl, 'walletsystem/index/index')
             !== false ? "current":"");?>">
           <?php
            if (strpos($magentoCurrentUrl, 'walletsystem/index/index') !== false) { ?>
                <strong><?=$escaper->escapeHtml(__('Manage Wallet Amount')) ?></strong>
                <?php
            } else { ?>
                <a href="<?=$escaper->escapeUrl($block->getUrl('walletsystem/index/index')); ?>">
                    <?=$escaper->escapeHtml(__('Manage Wallet Amount')) ?>
                </a>
                <?php
            } ?>
            </li>
            <li
            class="nav item <?= $escaper->escapeHtml(strpos($magentoCurrentUrl, 'walletsystem/transfer/index')
            !== false ? "current":"");?>">
           <?php
            if (strpos(
                $magentoCurrentUrl,
                'walletsystem/transfer/index'
            ) !== false) { ?>
                <strong><?=$escaper->escapeHtml(__('Transfer Wallet Amount')) ?></strong>
                <?php
            } else { ?>
                <a href="<?=$escaper->escapeUrl($block->getUrl('walletsystem/transfer/index')); ?>">
                    <?=$escaper->escapeHtml(__('Transfer Wallet Amount')) ?>
                </a>
                <?php
            } ?>
            </li>
            <li class="nav item 
                <?=
                $escaper->escapeHtml(
                    strpos($magentoCurrentUrl, 'walletsystem/transfer/accountdetails')
                    !== false ? "current":""
                );
                ?>">
           <?php
            if (strpos($magentoCurrentUrl, 'walletsystem/transfer/accountdetails') !== false) { ?>
                <strong><?=$escaper->escapeHtml(__('Add Account Details')) ?></strong>
                <?php
            } else { ?>
                <a href="<?=$escaper->escapeUrl($block->getUrl('walletsystem/transfer/accountdetails')); ?>">
                    <?=$escaper->escapeHtml(__('Add Account Details')) ?>
                </a>
                <?php
            } ?>
            </li>
        </ul>
    </li>
<?php }?>
