<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Walletsystem
 * @author    Webkul
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

?>
<?php
use \Webkul\Walletsystem\Model\Wallettransaction;

$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
if ($helper->getWalletenabled()) {
        $status = 0;
        $customerId = $helper->getCustomerId();
        $currency_code = $helper->getCurrentCurrencyCode();
        $transactionData = $block->getTransactionData();
        $paymentTitle = "";
        $reason = "";
        $prefix = $helper->getTransactionPrefix($transactionData->getSenderType(), $transactionData->getAction()); ?>
        <div class="wk_ws_main">
            <div class='wk_ws_main_head'>
                <div class="wk_ws_sub_head1">
                    <img src='<?=$escaper->escapeUrl($block->getViewFileUrl(
                        'Webkul_Walletsystem::images/wallet.png'
                    ));?>' width="70px" height="55px">
                </div>
                <div class="wk_ws_sub_head2">
                <h2><?=$escaper->escapeHtml(__('Wallet Details'));?></h2>
                <h3>
                    <span class="wk_ws_price">
                        <?=$escaper->escapeHtml($block->getWalletRemainingTotal($customerId))?>
                    </span>
                    <?= $escaper->escapeHtml("(".$currency_code.")")?>
                </h3>
                <span><?=$escaper->escapeHtml(__("Your Wallet Balance"))?></span>
                </div>
            </div>
            <div class='wk_ws_body'>
                <table class="wallet-transaction-view">
                    <tbody>
                        <tr>
                            <th><?=$escaper->escapeHtml(__("Amount"))?></th>
                            <td><?=/*@noEscape*/$block->getTransactionAmount($transactionData)?></td>
                        </tr>
                        <tr>
                            <th><?=$escaper->escapeHtml(__("Action"))?></th>
                            <td><?=$escaper->escapeHtml($transactionData->getAction())?></td>
                        </tr>
                        <tr>
                            <th><?=$escaper->escapeHtml(__("Type"))?></th>
                            <td><?=$escaper->escapeHtml(__($prefix))?></td>
                        </tr>
                        <?php
                        if ($transactionData->getOrderId()) {
                            $order = $block->getOrder()->load($transactionData->getOrderId());
                            $incrementid = $order->getIncrementId();
                            $paymentTitle = $order->getPayment()->getMethodInstance()->getTitle();
                        }
                            $orderDetailsActions = [
                                Wallettransaction::ORDER_PLACE_TYPE,
                                Wallettransaction::REFUND_TYPE
                            ];
                            if (in_array(
                                $transactionData->getSenderType(),
                                $orderDetailsActions
                            )) { ?>
                            <tr>
                                <th><?=$escaper->escapeHtml(__("Reference"))?></th>
                                <td><a href="
                                <?=$escaper->escapeUrl($block->getUrl(
                                    'sales/order/view/',
                                    ['order_id'=>$transactionData->getOrderId()]
                                ));?>"><?= $escaper->escapeHtml("#".$incrementid)?></a></td>
                            </tr>
                        <?php } elseif ($transactionData->getSenderType()==Wallettransaction::CASH_BACK_TYPE) {
                                if ($transactionData->getAction()==Wallettransaction::WALLET_ACTION_TYPE_CREDIT) { ?>
                                <tr>
                                    <th><?=$escaper->escapeHtml(__("Reference"))?></th>
                                    <td><a href="
                                    <?=$escaper->escapeUrl($block->getUrl(
                                        'sales/order/view/',
                                        ['order_id'=>$transactionData->getOrderId()]
                                    ));?>"><?= $escaper->escapeHtml("#".$incrementid)?></a></td>
                                </tr>
                        <?php }
                        } elseif ($transactionData->getSenderType()==Wallettransaction::CUSTOMER_TRANSFER_TYPE) {
                            if ($transactionData->getAction()==Wallettransaction::WALLET_ACTION_TYPE_CREDIT) {
                                $senderData = $block->getCustomerDataById($transactionData->getSenderId()); ?>
                                <tr>
                                    <th><?=$escaper->escapeHtml(__("Sender"))?></th>
                                    <td>
                                        <?=$escaper->escapeHtml(__($senderData->getFirstname()." "
                                        .$senderData->getLastname()))?>
                                    </td>
                                </tr>
                        <?php } else {
                                $recieverData = $block->getCustomerDataById(
                                    $transactionData->getSenderId()
                                );
                                if ($recieverData->getEntityId()):
                                    ?>
                                <tr>
                                    <th><?=$escaper->escapeHtml(__("Receiver"))?></th>
                                    <td>
                                        <?=$escaper->escapeHtml(__($recieverData->getFirstname()." ".
                                        $recieverData->getLastname()))?>
                                    </td>
                                </tr>
                            <?php else: ?>
                                <tr>
                                    <th><?=$escaper->escapeHtml(__("Receiver"))?></th>
                                    <td><?=$escaper->escapeHtml(__("Reciever not exists"))?></td>
                                </tr>
                            <?php endif;?>
                        <?php }
                        } elseif ($transactionData->getSenderType()==Wallettransaction::CUSTOMER_TRANSFER_BANK_TYPE) {?>
                            <tr>
                                <th><?=$escaper->escapeHtml(__("Bank Details"))?></th>
                                <td>
                                    <?=/*@noEscape*/ $helper->getbankDetails(
                                        nl2br($transactionData->getBankDetails())
                                    )?>
                                </td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <th><?=$escaper->escapeHtml(__("Transaction At"))?></th>
                            <?php $date = $block->formatDate(
                                $transactionData->getTransactionAt(),
                                \IntlDateFormatter::LONG
                            );?>
                            <td><?=$escaper->escapeHtml($date)?></td>
                        </tr>
                        <tr>
                            <th><?=$escaper->escapeHtml(__("Transaction note"))?></th>
                            <td><?=/*@noEscape*/$transactionData->getTransactionNote()?></td>
                        </tr>
                        <tr>
                            <th><?=$escaper->escapeHtml(__("Transaction Status"))?></th>
                            <td>
                                <?php
                                $transactionStatus = "";
                                if ($transactionData->getStatus()==Wallettransaction::WALLET_TRANS_STATE_PENDING):
                                    $transactionStatus = $escaper->escapeHtml(__('Pending'));
                                 elseif ($transactionData->getStatus()==Wallettransaction::WALLET_TRANS_STATE_CANCEL):
                                     $reason = ($block->getTransactionAdditionalData())?
                                     $block->getTransactionAdditionalData():"";
                                     $transactionStatus = $escaper->escapeHtml(__('Cancelled'));
                                 else:
                                     $transactionStatus = $escaper->escapeHtml(__('Approved'));
                                 endif; ?>
                                 <?=/*@noEscape*/ $transactionStatus?>
                            </td>
                        </tr>
                        <?php if ($helper->isRechargeTrasaction(
                            $transactionData->getAction(),
                            $transactionData->getSenderType()
                        )): ?>
                            <tr>
                                <th><?=$escaper->escapeHtml(__("Payment Method"))?></th>
                                <td><?=$escaper->escapeHtml($paymentTitle)?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($reason && $reason != ""): ?>
                            <tr>
                                <th><?=$escaper->escapeHtml(__("Reason"))?></th>
                                <td><?=$escaper->escapeHtml($reason)?></td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
<?php }?>
<div class="buttons-set">
    <p class="back-link">
        <a href="javascript:;"
         onclick="javascript: window.history.back();"
         class="left">&laquo; <?=$escaper->escapeHtml(__('Back')) ?></a>
    </p>
</div>
