<?php /** * Copyright © MageWorx. All rights reserved. * See LICENSE.txt for license details. */ /** @var $block \MageWorx\SocialProofBase\Block\Adminhtml\Campaign\StepsWizard\Wrapper */ ?> <?= /* @noEscape */ $block->getStepsWizard(); ?> <script>
    require(['jquery', 'uiRegistry', 'underscore'], function ($, registry, _) {
        $('body').trigger('contentUpdated');
        $('[data-role=steps-wizard-main]').applyBindings();

        registry.async('<?= /* @noEscape */ $block->getData('config/stepsWizardName') ?>')(function (component) {
            _.delay(component.open.bind(component), 500); 
        })
    });</script>