<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$bannerDisplay      =   $helper->getDisplayBannerLayout2();
$bannerImage        =   $helper->getBannerImageLayout2();
$bannerContent      =   $helper->getBannerContentLayout2();
$marketplacebutton  =   $helper->getBannerButtonLayout2();
$sellerAccountUrl   =   $block->getUrl(
    'marketplace/account/becomeseller',
    ["_secure" => $block->getRequest()->isSecure()]
);
if (!$helper->isCustomerLoggedIn()) {
    $sellerAccountUrl = '#register-as-seller';
} ?>
<link rel="stylesheet" type="text/css" href="<?= /* @noEscape */ $block
->getViewFileUrl('Webkul_Marketplace::css/landingpage_one.css');?>">
<div class="wk-mp-design wk-mp-landingpage wk-mp-landingpage-layout2">
    <?php if ($bannerDisplay): ?>
        <div class="wk-mp-banner-container-layout2">
            <div class="wk-mp-banner">
                <div class="wk-mp-header">
                    <?= /* @noEscape */ $block->getCmsFilterContent($bannerContent)?>
                    <p>
                        <a href="<?= $escaper->escapeUrl($sellerAccountUrl)?>">
                            <button class="button wk-mp-landing-button">
                                <span>
                                    <span>
                                        <strong><?= $escaper->escapeHtml($marketplacebutton); ?></strong>
                                    </span>
                                </span>
                            </button>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?= $block->getLayout()
          ->createBlock(Magento\Cms\Block\Block::class)
          ->setBlockId('marketplace_layout2')
          ->toHtml();?>
    <div class="wk-list-container-class">
        <div class="wk-list-container-wrapper wk-text-transform-left">
            <div class="wk-list-container">
                <div class="wk-list-container-feature-label">
                    <?= $escaper->escapeHtml(__('Really Easy To Setup And Customize'));?>
                </div>
                <ul>
                    <li class="wk-icon-check">
                        <span class="wk-icon-check-span">
                            <?= $escaper->escapeHtml(__('Create an Account'));?>
                        </span>
                    </li>
                    <li class="wk-icon-check">
                        <span class="wk-icon-check-span">
                            <?= $escaper->escapeHtml(__('Create your Profile'));?>
                        </span>
                    </li>
                    <li class="wk-icon-check">
                        <span class="wk-icon-check-span">
                            <?= $escaper->escapeHtml(__('Add your Details'));?>
                        </span>
                    </li>
                    <li class="wk-icon-check">
                        <span class="wk-icon-check-span">
                            <?= $escaper->escapeHtml(__('Add your Product Listing'));?>
                        </span>
                    </li>
                    <li class="wk-icon-check">
                        <span class="wk-icon-check-span">
                            <?= $escaper->escapeHtml(__('Sell your Products and Earn Points'));?>
                        </span>
                    </li>
                </ul>
            </div>
            <?php if (!$helper->isCustomerLoggedIn()): ?>
                <div class="wk-list-container wk-list-container-registration" id="register-as-seller">
                    <div class="wk-list-container-feature-label">
                        <?= $escaper->escapeHtml(__('Register As Seller'))?>
                    </div>
                    <?= $block->getChildHtml('customer_form_register');?>

                </div>
            <?php endif; ?>
        </div>
    </div>
    <div class="wk-list-container-wrapper wk-text-transform-center">
        <span class="wk-icon-check-span">
            <?= $escaper->escapeHtml(__('Open your own online shop & explore a new world of 
         marketplace with more and millions of shoppers'))?></span>
        <div class="primary">
            <a href="<?= $escaper->escapeUrl($sellerAccountUrl)?>">
                <button type="submit" class="action submit primary"
                title="<?= $escaper->escapeHtml(__('Open Your Shop'))?>">
                    <span><?= $escaper->escapeHtml(__('Open Your Shop'))?></span>
                </button>
            </a>
        </div>
    </div>
</div>
<script>
    require([
        "jquery",
        "mage/mage",
    ], function($){
        $('.page-title-wrapper').hide();
        $('.wk-mp-banner').css('background-image','url("<?= $escaper->escapeUrl($bannerImage) ?>")');
    });
</script>
