<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$multiselectName = "marketplace_product_attributes_listing.".
"marketplace_product_attributes_listing.product_attributes_columns.ids";
$providerName = "marketplace_product_attributes_listing.marketplace_product_attributes_listing_data_source";
?>
<div class="select-attributes-block">
    <div class="select-attributes-actions" data-type="skipKO">
    </div>
    <h2 class="steps-wizard-title"><?= $escaper->escapeHtml(__('Step 1: Select Attributes')) ?></h2>
    <div class="selected-attributes" data-bind="scope: 'variation-steps-wizard_step1'">
        <?= $escaper->escapeHtml(__('Selected Attributes:')) ?>
        <span data-bind="text: selectedAttributes() || '--'"></span>
    </div>
</div>
<?= $block->getChildHtml(); ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "variation-steps-wizard_step1": {
                        "component": "Webkul_Marketplace/js/variations/steps/select_attributes",
                        "multiselectName": "<?= $escaper->escapeHtml($multiselectName) ?>",
                        "providerName": "<?= $escaper->escapeHtml($providerName) ?>",
                        "appendTo": "variation-steps-wizard"
                    }
                }
            }
        }
    }
</script>
