<?php
/**
 * Copyright © 2018 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \MageWorx\PersonalPromotion\Block\Adminhtml\Promo\PromoCustomers $block */
/** @var \MageWorx\PersonalPromotion\Block\Adminhtml\Promo\Tab\Customers $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="promo_customers" id="in_promo_customers" data-form-part="sales_rule_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "MageWorx_PersonalPromotion/promo/assign-customers": {
                "namePromoCustomers": "in_promo_customers",
                "selectedCustomers": <?= /* @noEscape */ $block->getCustomersJson() ?>,
                "gridJsObjectName": <?= '"' . $block->escapeJs($gridJsObjectName) . '"' ?: '{}' ?>
            }
        }
    }
</script>
<script>
    require('mage/apply/main').apply();
</script>