<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>

<li class="item link compare" data-bind="scope: 'pointsUpcoming'" data-role="points-upcoming-message">
    <!-- ko if: pointsUpcoming().enable -->
    <div class="mwrp-banner block-content no-display" aria-labelledby="block-compare-heading" data-bind="css: {'no-display': !pointsUpcoming().enable}">
        <div class="mwrp-banner__content" data-bind="html: pointsUpcoming().message"></div>
    </div>
    <!-- /ko -->
</li>

<script type="text/x-magento-init">
{"[data-role=points-upcoming-message]": {"Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>}}
</script>