<?php if ($block->getHelper()->isEnabledExtension() && $block->getHelper()->displayTopMenu()) { ?>
    <div id="ordertracking_container">
        <li id="ordertracking-menu" class="level0 nav-2 level-top ui-menu-item" role="presentation"><a
                    href="<?= $block->escapeHtmlAttr(__($block->getUrl('ordertracking'))) ?>"
                    class="level-top ui-corner-all" role="menuitem"
                    tabindex="-1"><span><?= $block->escapeHtml(__('Track Your Order')) ?></span></a></li>
    </div>
    <script type="text/javascript">
        require([
            "jquery",
            "mage/mage"
        ], function (jQuery) {
            jQuery(document).ready(function () {
                var menu = jQuery('.navigation');
                if (menu) {
                    var current_menu = jQuery(jQuery('.navigation').find('ul')[0]).html();
                    jQuery(jQuery('.navigation').find('ul')[0]).html(current_menu +
                        jQuery('#ordertracking_container').html())
                }
            });

        });
    </script>
<?php } ?>