<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$orderHelper = $viewModel->getOrderHelper();
$orderId = $block->getRequest()->getParam('id');
$order = $block->getOrder();
$paymentCode = '';
$paymentMethod = '';
if ($order->getPayment()) {
    $paymentCode = $order->getPayment()->getMethod();
    $paymentMethod = $order->getPayment()->getMethodInstance()->getTitle();
}
$codMsg = "If you pay admin commission then you can not do refund for buyer in future.".
" Are you sure you want to pay admin for his commission?";
$marketplaceOrders = $block->getSellerOrderInfo($orderId);
if (count($marketplaceOrders)) {
    $adminPayStatus = $block->getAdminPayStatus($orderId);
    $itemCollection = $block->getOrderItemCollection($orderId);
    $qtyToInvoiceAvail = $block->getQtyToInvoiceCount($itemCollection);
    $qtyToShipAvail = $block->getQtyToShipCount($itemCollection);
    $qtyToCancelAvail = $block->getQtyToCancelCount($itemCollection);
    //$qtyToRefundAvail = $block->getQtyToRefundCollection($orderId);
    $qtyToRefundAvail = $block->getQtyToRefundCount($itemCollection);

    $tracking = $orderHelper->getOrderinfo($orderId);
    $orderStatus = strtoupper(__($marketplaceOrders->getData()[0]['order_status']));
    if ($tracking != "") {
        $disabled = $tracking->getTrackingNumber()==''? "":"readonly='readonly'";
        $shipmentId = $tracking->getShipmentId();
        $invoiceId=$tracking->getInvoiceId();
        $creditmemoId=$tracking->getCreditmemoId();

        $isCanceled=$tracking->getIsCanceled();
        if ($shipmentId) {
            $itemShipStatus = 'Shipped';
        } else {
            $itemShipStatus = '';
        }
        if ($invoiceId) {
            $itemInvoiceStatus = 'Invoiced';
        } else {
            $itemInvoiceStatus = '';
        }
        if ($creditmemoId && !$qtyToRefundAvail) {
            $shippingamount=$tracking->getShippingCharges();
            $refundedShippingAmount=$tracking->getRefundedShippingCharges();
            if ($shippingamount-$refundedShippingAmount == 0) {
                $itemRefundStatus = 'Refunded';
            } else {
                $itemRefundStatus = '';
            }
        } else {
            $itemRefundStatus = '';
        }

        $itemCancelStatus = $isCanceled;

        $invoiceId = $tracking->getInvoiceId();
    }
    ?>
    <div class="wk-mp-design">
        <div class="fieldset wk-mp-fieldset">
            <div class="page-title-wrapper">
                <h1 class="page-title">
                    <span data-ui-id="page-title-wrapper" class="base">
                        <?= $escaper->escapeHtml(__('Manage Order # %1', $order->getRealOrderId())) ?>
                    </span>
                </h1>
                <div class="wk-dash-orderstatus order-view">
                    <label for="name" class="wk-dash-label">
                            <div 
                            class="status <?= $escaper
                            ->escapeHtml(strtolower($marketplaceOrders->getData()[0]['order_status'])); ?>">
                            <?= $escaper->escapeHtml($orderStatus); ?>
                            </div>
                    </label>
                </div>
                
                <div class="order-date">
                <span class="label"><?= $escaper->escapeHtml(__("Order Date"))?>:</span>
                <date><?= /* @noEscape */ $block
                    ->formatDate($order->getCreatedAt(), \IntlDateFormatter::MEDIUM, true, $block
                    ->getTimezoneForStore($order->getStore())) ?>
                </date>
                </div>
                <div class="actions-toolbar order-actions-toolbar">
                    <div class="actions">
                        <a onclick="this.target='_blank';" href="<?= $escaper->escapeUrl($block
                        ->getUrl('marketplace/order/printorder', ['id'=>$orderId, '_secure' => $block
                        ->getRequest()->isSecure()]));?>" class="action">
                            <button class="button wk-mp-btn " title="<?= $escaper->escapeHtml(__('Print')) ?>"
                             type="submit" id="save_butn" >
                                <span><span><?= $escaper->escapeHtml(__('Print')) ?></span></span>
                            </button>
                        </a>
                        <?php if ($itemCancelStatus!="1" && $order->canCancel()) {?>
                            <a href="<?= $escaper->escapeUrl($block
                            ->getUrl('marketplace/order/cancel', ['id'=>$orderId, '_secure' => $block
                            ->getRequest()->isSecure()]))?>"
                            onclick="return confirm('<?=
                                                        $escaper->escapeHtml(
                                                            __("Are you sure you want to cancel this order?")
                                                        )
                                                        ?>')" class="action">
                                <button class="button wk-mp-btn" title="<?= $escaper->escapeHtml(__('Cancel Order')) ?>"
                                 type="button">
                                    <span><span><?= $escaper->escapeHtml(__('Cancel Order')) ?></span></span>
                                </button>
                            </a>
                            <?php
                        } ?>
                        <?php if (($itemCancelStatus!="1" && !$order->isCanceled()) || $qtyToCancelAvail) { ?>
                            <a href="<?= $escaper->escapeUrl($block
                            ->getUrl('marketplace/order/email', ['id'=>$orderId, '_secure' => $block
                            ->getRequest()->isSecure()]))?>"
                            onclick="return confirm('<?=
                                                        $escaper->escapeHtml(
                                                            __("Are you sure you want to send order email to customer?")
                                                        )
                                                        ?>')" class="action">
                                <button class="button wk-mp-btn" 
                                title="<?= $escaper->escapeHtml(__('Send Email To Customer')) ?>"
                                 type="button">
                                    <span><span><?= $escaper->escapeHtml(__('Send Email')) ?></span></span>
                                </button>
                            </a>
                            <?php
                        } ?>
                        <?php if ($qtyToInvoiceAvail && $order->canInvoice()) {?>
                            <a href="<?= $escaper->escapeUrl($block
                            ->getUrl('marketplace/order_invoice/create', ['id'=>$orderId, '_secure' => $block
                            ->getRequest()->isSecure()]))?>"
                            onclick="return confirm('<?=
                                                            $escaper->escapeHtml(
                                                                __("Are you sure you want to create invoice?")
                                                            ) ?>')" class="action">
                                <button class="button wk-mp-btn" 
                                title="<?=
                                        $escaper->escapeHtml(
                                            __('Create Invoice to confirm collected amount from buyer for this order')
                                        ) ?>"
                                type="button">
                                    <span><span><?= $escaper->escapeHtml(__('Invoice')) ?></span></span>
                                </button>
                            </a>
                            <?php
                        }
                        if ($itemInvoiceStatus=="Invoiced" && $itemRefundStatus!="Refunded"
                         && $order->canCreditmemo()) {
                            if ($helper->isMpcashondeliveryModuleInstalled() &&
                             $paymentCode == 'mpcashondelivery' && !$adminPayStatus) { ?>
                                <a href="<?= $escaper->escapeUrl($block
                                ->getUrl('mpcashondelivery/order/payadmin', ['id'=>$orderId, '_secure' => $block
                                ->getRequest()->isSecure()]))?>" class="action">
                                    <button class="button wk-mp-btn"
                                    title="<?=
                                                $escaper->escapeHtml(
                                                    __('Pay Admin for his commission for this order')
                                                ) ?>" 
                                     onclick="return confirm('<?= $escaper->escapeHtml(__($codMsg)) ?>')" type="button">
                                        <span>
                                            <span>
                                                <?= $escaper->escapeHtml(__('Pay Admin Commission')) ?>
                                            </span>
                                        </span>
                                    </button>
                                </a>
                                <a href="<?= $escaper->escapeUrl($block
                                ->getUrl('marketplace/order_creditmemo/create', ['order_id'=>$orderId, '_secure'=>$block
                                ->getRequest()->isSecure()]))?>" class="action">
                                    <button class="button wk-mp-btn" 
                                    title="<?= $escaper->escapeHtml(__('Create Credit Memo')) ?>"
                                     type="button">
                                        <span><span><?= $escaper->escapeHtml(__('Credit Memo')) ?></span></span>
                                    </button>
                                </a>
                                <?php
                            } elseif ($paymentCode != 'mpcashondelivery') { ?>
                                <a href="<?= $escaper->escapeUrl($block
                                ->getUrl('marketplace/order_creditmemo/create', ['order_id'=>$orderId, '_secure'=>$block
                                ->getRequest()->isSecure()]))?>" class="action">
                                    <button class="button wk-mp-btn" 
                                    title="<?= $escaper->escapeHtml(__('Create Credit Memo')) ?>" type="button">
                                        <span><span><?= $escaper->escapeHtml(__('Credit Memo')) ?></span></span>
                                    </button>
                                </a>
                                <?php
                            }
                        } ?>
                        <?php
                        if ($qtyToShipAvail && $block->isOrderCanShip($order)) { ?>
                            <a href="<?= $escaper->escapeUrl($block
                                ->getUrl('marketplace/order_shipment/create', ['id'=>$orderId, '_secure' => $block
                                ->getRequest()->isSecure()]))?>"
                                onclick="return confirm('<?=
                                                            $escaper->escapeHtml(
                                                                __("Are you sure you want to create shipment?")
                                                            ) ?>')" class="action">
                                <button class="button wk-mp-btn" 
                                title="<?= $escaper->escapeHtml(__('Create Shipment for Order')) ?>"
                                type="button" id="mp-create-shipment-btn">
                                    <span><span><?= $escaper->escapeHtml(__('Ship')) ?></span></span>
                                </button>
                            </a>
                            <?php
                        } ?>
                    </div>
                </div>
            </div>
            <?php
            $_links = $block->getLinks();
            ?>
            <ul class="items order-links">
                <?php foreach ($_links as $_link): ?>
                    <?php if (strpos($_link['url'], "marketplace/order/view") === false): ?>
                        <li class="nav item">
                            <a href="<?= $escaper->escapeUrl($_link['url']) ?>">
                                <?= $escaper->escapeHtml($_link['label']) ?>
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="nav item current"><strong><?= $escaper->escapeHtml($_link['label']) ?></strong></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
            <div class="order-details-items ordered">
                <div class="order-title">
                    <strong><?= $escaper->escapeHtml(__('Items Ordered')) ?></strong>
                </div>
                <?= $block->getChildHtml('marketplace_order_items') ?>
            </div>
            <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                <div class="block block-order-details-view">
                    <div class="block-title">
                        <strong><?= $escaper->escapeHtml(__('Buyer Information')) ?></strong>
                    </div>
                    <div class="block-content">
                        <div class="box-content">
                            <div class="box">
                                <div class="wk-row">
                                    <span class="label"><?= $escaper->escapeHtml(__('Customer Name'))?> : </span>
                                    <span class="value"><?= $escaper->escapeHtml($order->getCustomerName()); ?></span>
                                </div>
                                <div class="wk-row">
                                    <span class="label"><?= $escaper->escapeHtml(__('Email'))?> : </span>
                                    <span class="value"><?= $escaper->escapeHtml($order->getCustomerEmail()); ?></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <div class="block block-order-details-view">
                <div class="block-title">
                    <strong><?= $escaper->escapeHtml(__('Order Information')) ?></strong>
                </div>
                <div class="block-content">
                    <?php if (!$order->getIsVirtual()): ?>
                        <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                            <div class="box box-order-shipping-address">
                                <strong class="box-title"><span>
                                    <?= $escaper->escapeHtml(__('Shipping Address')) ?></span></strong>
                                <div class="box-content">
                                    <address><?= /* @noEscape */ $block->getFormattedAddress($order
                                    ->getShippingAddress()); ?></address>
                                </div>
                            </div>
                            <?php
                        } ?>
                        <div class="box box-order-shipping-method">
                            <strong class="box-title">
                                <span><?= $escaper->escapeHtml(__('Shipping Method')) ?></span>
                            </strong>
                            <div class="box-content">
                            <?php if ($order->getShippingDescription()): ?>
                                <?= $escaper->escapeHtml($order->getShippingDescription()) ?>
                            <?php else: ?>
                                <?= $escaper->escapeHtml(__('No shipping information available')); ?>
                            <?php endif; ?>
                            </div>
                          
                        </div>
                    <?php endif; ?>
                    <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                        <div class="box box-order-billing-address">
                            <strong class="box-title">
                                <span><?= $escaper->escapeHtml(__('Billing Address')) ?></span>
                            </strong>
                            <div class="box-content">
                                <address><?= /* @noEscape */ $block->getFormattedAddress($order->getBillingAddress());?>
                            </address>
                            </div>
                        </div>
                        <?php
                    } ?>
                    <div class="box box-order-billing-method">
                        <strong class="box-title">
                            <span><?= $escaper->escapeHtml(__('Payment Method')) ?></span>
                        </strong>
                        <div class="box-content">
                            <?= $escaper->escapeHtml($paymentMethod); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="buttons-set">
        <p class="back-link">
            <a href="<?= $escaper->escapeUrl($block
            ->getUrl('marketplace/order/history', ['_secure' => $block
            ->getRequest()->isSecure()]));?>" 
            class="left">&laquo; <?= $escaper->escapeHtml(__('Back To My Orders')) ?></a>
        </p>
    </div>
    <?php
}
