<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$partner=[];
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$partner = $helper->getSeller();
$isPartner = $helper->isSeller();
if ($isPartner == 1) { ?>
    <div class="wk-mp-design">
        <fieldset class="fieldset info wk-mp-fieldset">
            <legend class="legend"><span>
                <?= $escaper->escapeHtml(__('Order Details of Product : %1', $block->getProduct()->getName()))?>
            </span></legend>
            <div class="order-details-items ordered">
                <div class="table-wrapper order-items">
                    <table class="data table table-order-items"
                        summary="<?= $escaper->escapeHtml(__('Order List Per Product')) ?>">
                        <thead>
                            <tr>
                                <th class="col price"><?= $escaper->escapeHtml(__('Order #')) ?></th>
                                <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                                    <th class="col price"><?= $escaper->escapeHtml(__('Buyer Name')) ?></th>
                                <?php } ?>
                                <th class="col price"><?= $escaper->escapeHtml(__('Sold on')) ?></th>
                                <th class="col price"><?= $escaper->escapeHtml(__('Action')) ?></th>
                                <th class="col price"><?= $escaper->escapeHtml(__('Download')) ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $index = 0;
                            foreach ($block->getCollection() as $marketplace_order) {
                                $index++;
                                $order_id = $marketplace_order->getOrderId();
                                $order = $block->getOrderById($order_id);
                                $shipment_id = 0;
                                $invoice_id = 0;
                                $invoice_id=$marketplace_order->getInvoiceId();
                                $shipment_id=$marketplace_order->getShipmentId();
                                ?>
                                <tr class="border">
                                    <td class="col price" data-th="<?= $escaper->escapeHtml(__('Order #')) ?>">
                                        <?= $escaper->escapeHtml($order['increment_id']);?>
                                    </td>
                                    <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                                        <td class="col price" data-th="<?= $escaper->escapeHtml(__('Buyer Name')) ?>">
                                            <?= $escaper->escapeHtml($order->getCustomerName());?>
                                        </td>
                                    <?php } ?>
                                    <td class="col price" data-th="<?= $escaper->escapeHtml(__('Sold on')) ?>">
                                    <?= $escaper->escapeHtml($block->formatDate($marketplace_order->getCreatedAt()));?>
                                    </td>
                                    <td class="col price" data-th="<?= $escaper->escapeHtml(__('View')) ?>">
                                        <a href="<?= $escaper->escapeUrl($block
                                        ->getUrl('marketplace/order/view', ['id'=>$order_id, '_secure' => $block
                                        ->getRequest()->isSecure()]))?>">
                                            <?= $escaper->escapeHtml(__('View Order'));?>
                                        </a>
                                    </td>
                                    <td class="col price" data-th="<?= $escaper->escapeHtml(__('Action')) ?>">
                                        <?php if ($shipment_id) { ?>
                                            <a href="<?= $escaper->escapeUrl($block
                                            ->getUrl(
                                                'marketplace/order_shipment/printpdf',
                                                ['order_id'=>$order_id,'shipment_id'=>$shipment_id,
                                                '_secure' => $block->getRequest()->isSecure()]
                                            ));?>"
                                               class="action">
                                                <?= $escaper->escapeHtml(__('Shipping Slip'));?>
                                            </a>
                                            <?php
                                        } else { ?>
                                            <span class="action">
                                                <?= $escaper->escapeHtml(__('Shipping Slip'));?>
                                            </span>
                                            <?php
                                        }
                                        if ($invoice_id) { ?>
                                            <a href="<?= $escaper->escapeUrl($block
                                            ->getUrl(
                                                'marketplace/order_invoice/printpdf',
                                                ['order_id'=>$order_id,'invoice_id'=>$invoice_id,
                                                '_secure' => $block->getRequest()->isSecure()]
                                            ));?>"  class="action">
                                                <?= $escaper->escapeHtml(__('Invoice Slip'));?>
                                            </a>
                                            <?php
                                        } else { ?>
                                            <span class="action">
                                                <?= $escaper->escapeHtml(__('Invoice Slip'));?>
                                            </span>
                                            <?php
                                        } ?>
                                    </td>
                                </tr>
                                <?php
                            }?>
                        </tbody>
                    </table>
                </div>
            </div>
            <?php if ($block->getPagerHtml()): ?>
                <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>
            <?php endif ?>
        </fieldset>
    </div>
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();"
             class="left">&laquo; <?= $escaper->escapeHtml(__('Back')) ?></a>
        </p>
    </div>
    <?php
} else { ?>
    <h2 class="wk-mp-error_msg">
        <?= $escaper->escapeHtml(__("To Become Seller Please Contact to Admin.")); ?>
    </h2>
    <?php
} ?>
