<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**
 * @var $toolbar \MageWorx\XReviewBase\Block\Review\Product\ListView\Toolbar
 */
$toolbar = $block->getParentBlock()->getParentBlock();
?>
<?php $customerCount = (int)$toolbar->getCustomerCount(); ?>
<div class="mw-sorting-controls__item toolbar-filter">
    <?php if ($toolbar->getCurrentFilterValue() == 'on') : ?>
        <input id="toolbar_customer_filter"
               type="checkbox"
               checked
               title="<?= $toolbar->escapeHtmlAttr(__('Discard filter by verified buyers')) ?>"
               data-role="filter"
               data-value="off"
            <?= !$customerCount ? 'disabled' : '' ?>
        />
    <?php else: ?>
        <input id="toolbar_customer_filter"
               type="checkbox"
               title="<?= $toolbar->escapeHtmlAttr(__('Set filter by verified buyers')) ?>"
               data-role="filter"
               data-value="on"
            <?= !$customerCount ? 'disabled' : '' ?>
        />
    <?php endif; ?>
    <label class="mw-text" for="toolbar_customer_filter">
        <?= $toolbar->escapeHtml(__('Verified buyers (%1)', $customerCount)) ?>
    </label>
</div>
