<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$helper = $block->getViewModel()->getHelper();
?>
<input type="hidden" name="seller_panel" 
    id="seller_panel" 
    data-form-part="customer_form" 
    value="<?= $escaper->escapeHtml($helper->getParam("seller_panel")); ?>" />
