<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
$_item = $block->getItem();
$product = $_item->getProduct();
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$_product=$product;
$seller_id = '';
$marketplaceProduct = $helper->getSellerProductDataByProductId($_product['entity_id']);
foreach ($marketplaceProduct as $value) {
    $seller_id = $value['seller_id'];
}
if ($seller_id!="") {
    $rowsocial = $helper->getSellerDataBySellerId($seller_id);
    $shoptitle = '';
    $shop_url = '';
    foreach ($rowsocial as $value) {
        $shoptitle = $value['shop_title'];
        $shop_url = $value['shop_url'];
        if (!$shoptitle) {
            $shoptitle = $value->getShopUrl();
        }
    }
    $shoptitle = $escaper->escapeHtml($shoptitle);
    ?>
    <div class="wk-seller-block wk-block" id="mp-wk-block">
        <div>
            <span class="wk-block-font-bold-up"><?= $escaper->escapeHtml(__('Sold By'))?></span>
            <span class="wk-block-title-css">
                <a href="<?= $escaper->escapeUrl($helper
                ->getRewriteUrl('marketplace/seller/profile/shop/'.$shop_url));?>" 
                title="<?= $escaper->escapeHtml(__('Visit Shop')) ?>" id="profileconnect">
                <?= $escaper->escapeHtml($shoptitle); ?></a>
            </span>
        </div>
    </div>
    <?php
} ?>
