<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<img src="<?= $escaper->escapeUrl($block->getSellerStatisticsGraphUrl(true)) ?>" 
alt="<?= $escaper->escapeHtml(__("Seller Statistics Graph")); ?>" 
title="<?= $escaper->escapeHtml(__("Seller Statistics Graph")); ?>" id="wk-diagram-chart"/>
