<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block" 
    data-mage-init='{"collapsible":{"openedState": "active", 
        "collapsible": true, "active": false, 
        "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" 
        data-count="<?= $escaper->escapeHtml($filtered) ?>">
            <strong data-role="title"><?= $escaper->escapeHtml(__('Shop By')) ?></strong>
        </div>
        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $escaper->escapeUrl($block->getClearUrl()) ?>" 
                    class="action clear filter-clear"><span>
                        <?= $escaper->escapeHtml(__('Clear All')) ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <!-- for Seller Category Filter -->
            <?php if (!$wrapOptions): ?>
                <strong role="heading" aria-level="2" 
                class="block-subtitle filter-subtitle"><?= $escaper
                ->escapeHtml(__('Shopping Options')) ?></strong>
                <div class="filter-options" id="narrow-by-list"
                 data-role="content" 
                 data-mage-init='{"accordion":{"openedState": "active", 
                    "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                <?php  $wrapOptions = true;
endif; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle">
                            <?= $escaper->escapeHtml(__('Shopping Options')) ?></strong>
                        <div class="filter-options" id="narrow-by-list" 
                        data-role="content" 
                        data-mage-init='{"accordion":{"openedState": "active", 
                            "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                        <?php  $wrapOptions = true;
endif; ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title">
                            <?= /* @escapeNotVerified */ $escaper->escapeHtml(__($filter->getName())) ?></div>
                        <div data-role="content" class="filter-options-content">
                            <?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
