<?php /** * Webkul Software. * * @category Webkul * @package Webkul_Mpmembership * @author Webkul Software Private Limited * @copyright Webkul Software Private Limited (https://webkul.com) * @license https://store.webkul.com/license.html */ use Magento\Catalog\Model\Product\Visibility; use Webkul\Mpmembership\Model\Config\Source\Feeapplied; $helper = $block->getMembershipHelper(); $feeAppliedFor = $helper->getConfigFeeAppliedFor(); $params = $block->getParams(); $flag = false; if (!empty($params['id']) && $feeAppliedFor == Feeapplied::PER_PRODUCT) { $parentIds = $helper->getParentIdsByChildId($params['id']); if (!empty($parentIds)) { $flag = true; } } if ($flag): ?> <script type="text/x-magento-init">
        {
            "*": {
                "mpProductEdit": {
                    "visibility": <?= /* @noEscape */ Visibility::VISIBILITY_NOT_VISIBLE ?>
                }
            }
        }</script><?php endif; ?>