<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

// Daily deal Helper
$_dailydealhelper =$this->helper('Smartwave\Dailydeals\Helper\Data');

$_portohelper = $this->helper('Smartwave\Porto\Helper\Data');

$_category_config = $_portohelper->getConfig('porto_settings/category');
$_category_grid_config = $_portohelper->getConfig('porto_settings/category_grid');
$_product_label_config = $_portohelper->getConfig('porto_settings/product_label');
$_lazyload = $_portohelper->getConfig('porto_settings/optimization/lazyload');
$_inscrollAjax = $_portohelper->getConfig('layered_navigation/general/ajax_enable');
$_inscroll = $_portohelper->getConfig('layered_navigation/general/infinite_scroller');
$_inscroll_mode = $_portohelper->getConfig('layered_navigation/general/infinite_mode');

$_content_pos1 = isset($_category_grid_config['product_content_pos1']) ? $_category_grid_config['product_content_pos1'] : 'left';
$_button_pos = isset($_category_grid_config['product_button_pos']) ? $_category_grid_config['product_button_pos'] : 'top';
$_button_action = isset($_category_grid_config['product_button_action']) ? $_category_grid_config['product_button_action'] : 'top';
$_icon_only1 = isset($_category_grid_config['product_icon_only1']) ? $_category_grid_config['product_icon_only1'] : '0';
$_icon_only2 = isset($_category_grid_config['product_icon_only2']) ? $_category_grid_config['product_icon_only2'] : '0';
$_block_pos = isset($_category_grid_config['product_block_pos']) ? $_category_grid_config['product_block_pos'] : 'default';
$_quantity_pos = isset($_category_grid_config['product_quantity_pos']) ? $_category_grid_config['product_quantity_pos'] : 'below';
$_content_pos2 = isset($_category_grid_config['product_content_pos2']) ? $_category_grid_config['product_content_pos2'] : 'default';
$_link_pos = isset($_category_grid_config['product_link_pos']) ? $_category_grid_config['product_link_pos'] : 'default';
$_box_style = isset($_category_grid_config['product_box_style']) ? $_category_grid_config['product_box_style'] : 'box_shadow';
?>
<?php $iterator = 1; ?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $hover_image = 'category_page_grid-hover';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $columns = 'columns'.$_category_grid_config['columns'];
        $product_type = $_category_grid_config['product_type'];
        if($product_type == null) {
            $product_type = 1;
        }
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $hover_image = 'category_page_list-hover';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $columns = '';
        $product_type = 0;
    }
    $image_width = ($_category_config['ratio_width'])?$_category_config['ratio_width']:300;
    $image_height = ($_category_config['ratio_height'])?$_category_config['ratio_height']:300;
    $aspect_ratio = $_category_config['aspect_ratio'];
    if($aspect_ratio)
        $image_height = $image_width;
    ?>
    <div class="products wrapper <?php echo $viewMode; ?> <?php echo $columns; ?> products-<?php echo $viewMode; ?> <?php if($product_type == 2): ?>no-padding divider-line<?php endif; ?> <?php if($product_type == 5 || $product_type == 6 || $product_type == 7 || $product_type == 8): ?>no-padding<?php endif; ?> <?php if($product_type == 6): ?>divider-line<?php endif; ?>">
        <?php $iterator = 1; ?>
        <ol class="filterproducts products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <?php
                  $newType = array("13", "14", "15", "16", "17", "18", "19", "20");
                  $_type_class = '';
                    $_content_pos1 = '';
                  if(in_array($product_type, $newType)) {
                    $_content_pos1 = ' text-'.$_content_pos1;
                    $_type_class = ' product-type-advanced';
                    if($product_type == '15'){
                      $_type_class = ' product-type-advanced effect-ovdefault';
                      if($_button_action == 'top'){
                        $_content_pos1 = ' text-center';
                      }
                      if($_button_action == 'hide'){
                        $_content_pos1 = ' text-center hide-actions';
                      }
                    }
                    if($product_type == '16'){
                      $_type_class = ' product-type-advanced effect-hddf'.' box-'.$_block_pos;
                    }
                    if($product_type == '18'){
                      $_type_class = ' product-type-advanced effect-detailimg';
                      $_content_pos1 = ' text-left';
                      if($_content_pos2 == 'top'){
                        $_type_class = ' product-type-advanced effect-detailimg actions-bottom';
                      }
                      if($_content_pos2 == 'center'){
                        $_content_pos1 = ' text-center';
                        $_type_class = ' product-type-advanced effect-detailimg actions-center';
                      }
                      if($_content_pos2 == 'bottom'){
                        $_type_class = ' product-type-advanced effect-detailimg actions-top';
                      }
                    }
                    if($product_type == '19'){
                      $_type_class = ' product-type-advanced effect-cartlink';
                      if($_link_pos == 'image') {
                        $_type_class = ' product-type-advanced effect-cartlink cartlink-image';
                      }
                      $_content_pos1 = ' text-left';
                    }
                    if($product_type == '20'){
                      $_content_pos1 = ' text-center';
                      if($_box_style == 'box_shadow') {
                        $_type_class .= ' product-type-advanced effect-bheshadow';
                      }
                      if($_box_style == 'box_full') {
                        $_type_class .= ' product-type-advanced effect-bhesfd';
                        $_content_pos1 = ' text-left';
                      }
                      if($_box_style == 'box_border') {
                        $_type_class .= ' product-type-advanced effect-bheborder';
                      }
                      if($_box_style == 'box_border_padding') {
                        $_type_class .= ' product-type-advanced effect-bhebrspace';
                      }
                    }
                  }
                ?>
                <div class="product-item-info type<?php echo $product_type; ?><?= $_content_pos1;?> porto-tb-item type-product has-post-thumbnail product-type-simple" data-container="product-grid">
                  <div class="porto-section<?=$_type_class?> p-0">
                    <?php if($product_type == '20' && $_box_style == 'box_full'):?><div class="content-shadow"></div><?php endif;?>
                    <div class="product photo product-item-photo<?php if(in_array($product_type, $newType)):?> porto-tb-featured-image tb-image-type-hover<?php endif;?> product-image">
                      <div class="porto-tb-featured-image tb-image-type-hover">
                        <a href="<?php echo $_product->getProductUrl() ?>" tabindex="-1" class="post featured image">
                        <?php
                            if($aspect_ratio)
                                $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                            else
                                $productImage = $_imagehelper->init($_product, $image)->resize($image_width, $image_height);
                            $productImageUrl = $productImage->getUrl();
                        ?>
                        <img class="product-image-photo default_image <?php if(!$_lazyload): ?>porto-lazyload<?php endif;?>" <?php if(!$_lazyload): ?>data-<?php endif; ?>src="<?php echo $productImageUrl; ?>" width="<?php echo $image_width; ?>" height="<?php echo $image_height; ?>" alt="<?php //echo $productImage->getLabel();?>"/>
                        <?php if($_category_config['alternative_image']): ?>
                        <?php
                            if($aspect_ratio)
                                $productHoverImage = $_imagehelper->init($_product, $hover_image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                            else
                                $productHoverImage = $_imagehelper->init($_product, $hover_image)->resize($image_width, $image_height);
                            $productHoverImageUrl = $productHoverImage->getUrl();
                        ?>
                            <?php if($productImageUrl != str_replace("/thumbnail/","/small_image/",$productHoverImageUrl)): ?>
                            <img class="product-image-photo hover_image" src="<?php echo $productHoverImageUrl; ?>" width="<?php echo $image_width; ?>" height="<?php echo $image_height; ?>" alt="<?php //echo $productHoverImage->getLabel();?>"/>
                            <?php endif; ?>
                        <?php endif; ?>
                        </a>
                        <?php
                            $product_label = "";
                            if($_product_label_config['sale_label']) {
                                if ($percentage = $_portohelper->getPercentage($_product)) {
                                    if($_product_label_config['sale_label_percent']) {
                                        $product_label .= '<div class="product-label sale-label">'.$percentage.'%'.'</div>';
                                    } else {
                                        $product_label .= '<div class="product-label sale-label">'.$_product_label_config['sale_label_text'].'</div>';
                                    }
                                }
                            }
                            if($_product_label_config['new_label']) {
                                $now = date("Y-m-d");
                                $newsFrom= substr($_product->getData('news_from_date')?$_product->getData('news_from_date'):'',0,10);
                                $newsTo=  substr($_product->getData('news_to_date')?$_product->getData('news_to_date'):'',0,10);

                                if ($newsTo != '' || $newsFrom != ''){
                                    if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)) {
                                        $product_label .= '<div class="product-label new-label">'.$_product_label_config['new_label_text'].'</div>';
                                    }
                                }
                            }
                            if($product_label)
                                echo '<div class="product-labels">'.$product_label.'</div>';
                        ?>
                        <?php
                        $_show_actions_top = false;
                        $_product_inner_class = '';
                        if(in_array($product_type, ['3','5','6','7','8','9','11','13','14','15','16','17','18','19','20'])) {
                          $_show_actions_top = true;
                          if($product_type == 14 && $_button_pos == 'outside'){
                            $_show_actions_top = false;
                          }
                          if($product_type >= 13){
                            $_product_inner_class = ' tb-hover-content with-link';
                          }

                          if($product_type == 13 || ($product_type == 15 && $_button_action == 'top') || $product_type == 16 || $product_type == 17 || $product_type == 19) {
                            $_product_inner_class .= ' css-bottom-iconcart icon-absolute';
                          }
                          if($product_type == 14 && $_icon_only1){
                            $_product_inner_class .= ' show-cart-icon';
                          }
                          if($product_type == 14 && $_button_pos != 'outside'){
                            $_product_inner_class .= ' button-pos-'.$_button_pos;
                          }
                          if($product_type == 15 && $_icon_only2 && $_button_action != 'top'){
                            $_product_inner_class .= ' show-cart-icon';
                          }
                          if($product_type == 15 && $_button_action != 'top') {
                            $_product_inner_class .= ' button-pos-center';
                          }
                          if($product_type == 18) {
                            $_product_inner_class .= ' icon-absolute show-cart-icon';
                          }
                          if($product_type == 20 && $_box_style != 'box_full') {
                            $_product_inner_class .= ' css-bottom-iconcart icon-absolute';
                          }
                          if($product_type == 20 && $_box_style == 'box_full'){
                            $_show_actions_top = false;
                          }
                        }
                        if($_show_actions_top): ?>
                        <div class="product-item-inner<?= $_product_inner_class;?>">
                            <?php if(in_array($product_type, $newType)):?>
                            <a aria-label="post content" href="<?php echo $_product->getProductUrl() ?>" class="porto-tb-link"></a>
                            <?php endif;?>
                            <?php if($product_type == 15 || $product_type == 16 || $product_type == 18):?>
                              <?php if(($product_type == 15 && $_button_action == 'center') || ($product_type == 18 && $_content_pos2 == 'default') || ($product_type == 18 && $_content_pos2 == 'center')):?>
                              <div class="porto-section content-top">
                                <?php $_productNameStripped =  $block->stripTags($_product->getName(), null, true); ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php echo $_product->getProductUrl() ?>">
                                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
                                <?php if($_category_config['rating_star']): ?>
                                <?php
                                    $review_html = $block->getReviewsSummaryHtml($_product, $templateType);
                                ?>
                                <?php if($review_html): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                <?php else: ?>
                                <div class="product-reviews-summary short">
                                    <div class="rating-summary">
                                        <span class="label"><span>Rating:</span></span>
                                        <div class="rating-result" title="0%">
                                            <span style="width:0"><span>0%</span></span>
                                        </div>
                                    </div>
                                </div>
                                <?php endif; ?>
                                <?php endif; ?>
                              </div>
                              <?php endif; ?>
                              <div class="product details product-item-details porto-section<?php if($_button_action == 'top' || $_button_action == 'hide' || $product_type == 16):?> product-content<?php endif;?><?php if($product_type == 15 && $_button_action == 'center'):?> content-bottom<?php endif;?><?php if($product_type == 16 && $_block_pos == 'full'):?> d-flex justify-content-center flex-column<?php endif;?>">
                                <?php if($_button_action == 'top' || $_button_action == 'hide' || $product_type == 16  || ($product_type == 18 && $_content_pos2 == 'top')  || ($product_type == 18 && $_content_pos2 == 'bottom')):?>
                                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php echo $_product->getProductUrl() ?>">
                                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
                                <?php if($_category_config['rating_star']): ?>
                                <?php
                                    $review_html = $block->getReviewsSummaryHtml($_product, $templateType);
                                ?>
                                <?php if($review_html): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                <?php else: ?>
                                <div class="product-reviews-summary short">
                                    <div class="rating-summary">
                                        <span class="label"><span>Rating:</span></span>
                                        <div class="rating-result" title="0%">
                                            <span style="width:0"><span>0%</span></span>
                                        </div>
                                    </div>
                                </div>
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php endif;?>

                                <?php if($_category_config['product_price']): ?>
                                <?php echo $block->getProductPrice($_product) ?>
                                <?php endif; ?>
                                <?php echo $block->getProductDetailsHtml($_product); ?>
                                <?php if($product_type == 16):?>
                                  <div class="actions-primary">
                                      <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                  </div>
                                <?php endif;?>
                              </div>
                            <?php endif; ?>
                            <div class="product actions product-item-actions<?php if($product_type == 14 || ($product_type == 15 && $_button_action != 'top') || $product_type == 16 || $product_type == 17):?> d-flex align-items-center justify-content-center<?php endif;?><?php if($product_type == 17 && $_quantity_pos == 'image_center'):?> actions-center<?php endif;?>">
                              <?php
                                $c_show_cart = false;
                                if($product_type != 16){
                                  $c_show_cart = true;
                                }
                                if($product_type == 17 && ($_quantity_pos =='below' || $_quantity_pos =='above')) {
                                  $c_show_cart = false;
                                }
                                if($product_type == 19 && $_link_pos != 'image') {
                                  $c_show_cart = false;
                                }
                              ?>
                              <?php if($c_show_cart):?>
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post" class="d-flex flex-column flex-sm-row">
                                            <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php if($product_type == 17 && ($_quantity_pos == 'image_bottom' || $_quantity_pos == 'image_center')):?>
                                                <div class="qty-box">
                                                    <a href="javascript:void(0)" class="qtyminus"><i class="porto-icon-minus"></i></a>
                                                    <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                                                    <a href="javascript:void(0)" class="qtyplus"><i class="porto-icon-plus"></i></a>
                                                </div>
                                            <?php endif;?>
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                              <?php endif;?>
                                <?php if ($block->getMode() == 'grid'): ?>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                  <?php if($_category_config['addtowishlist']): ?>
                                    <a href="#"
                                       class="action towishlist actions-secondary"
                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button">
                                        <span><?php echo __('Add to Wish List') ?></span>
                                    </a>
                                  <?php endif; ?>
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php if($_category_config['addtocompare']): ?>
                                <?php
                                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                ?>
                                <a href="#"
                                   class="action tocompare actions-secondary"
                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                   data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                   role="button">
                                    <span><?php echo __('Add to Compare') ?></span>
                                </a>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php if($product_type != 13 && $product_type != 14 && $product_type != 17 && $product_type != 18 && $product_type != 20): ?>
                        <!-- Dailydeal Product data -->
                        <?php if($_dailydealhelper->isDealProduct($_product->getId())) : ?>
                        <?php $unique_id = rtrim(base64_encode(md5(microtime())),"="); ?>
                        <input type="hidden" id="todate_<?php echo $unique_id; ?>" value="<?php echo $_dailydealhelper->getDailydealToDate($_product->getSku()); ?>" >
                        <input type="hidden" id="fromdate_<?php echo $unique_id; ?>" value="<?php echo $_dailydealhelper->getDailydealFromDate($_product->getSku()); ?>">
                        <div class="sw-dailydeal-wrapper" style="display:none;" data-unique-id="<?php echo $unique_id; ?>">
                            <div class="sw-dailydeal">
                                <p id="expired_<?php echo $unique_id; ?>"></p>
                                <div class="countdowncontainer countdowncontainer_<?php echo $unique_id; ?>" style="display:none;">
                                    <span class="dailydeal-label">
                                        <?php echo __('Ends In:'); ?>
                                    </span>
                                    <span class="number-wrapper">
                                        <div class="line"></div>
                                        <span class="number day"><p id="countdown_days_<?php echo $unique_id; ?>">00</p></span>
                                        <div class="caption"><?php echo __('Day(s), '); ?></div>
                                    </span>

                                    <span class="number-wrapper">
                                        <div class="line"></div>
                                        <span class="number hour"><p id="countdown_hours_<?php echo $unique_id; ?>">00</p></span>
                                        <div class="caption">:</div>
                                    </span>

                                    <span class="number-wrapper">
                                        <div class="line"></div>
                                        <span class="number min"><p id="countdown_minutes_<?php echo $unique_id; ?>">00</p></span>
                                        <div class="caption">:</div>
                                    </span>

                                    <span class="number-wrapper">
                                        <div class="line"></div>
                                        <span class="number sec"><p id="countdown_seconds_<?php echo $unique_id; ?>">00</p></span>
                                        <div class="caption"></div>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>
                        <!-- Dailydeal Product End -->
                        <?php endif;?>
                      </div>
                    </div>
                    <?php if($product_type != '15' && $product_type != 16  && $product_type != '18'): ?>
                    <div class="product details product-item-details porto-section product-content<?php if($product_type == '17' && $_quantity_pos =='above'):?> qty-above d-flex flex-column align-items-center<?php endif;?><?php if($product_type == '19' && ($_link_pos == 'top' || $_link_pos == 'hidden')){?> show-cartlink-top<?php }?>">
                      <?php if($product_type == '13' || $product_type == '14' || $product_type == '17' || $product_type == '20'): ?>
                        <!-- Dailydeal Product data -->
                        <?php if($_dailydealhelper->isDealProduct($_product->getId())) : ?>
                        <?php $unique_id = rtrim(base64_encode(md5(microtime())),"="); ?>
                        <input type="hidden" id="todate_<?php echo $unique_id; ?>" value="<?php echo $_dailydealhelper->getDailydealToDate($_product->getSku()); ?>" >
                        <input type="hidden" id="fromdate_<?php echo $unique_id; ?>" value="<?php echo $_dailydealhelper->getDailydealFromDate($_product->getSku()); ?>">
                        <div class="sw-dailydeal-wrapper product-type-countdown2" style="display:none;" data-unique-id="<?php echo $unique_id; ?>">
                            <div class="sw-dailydeal">
                                <p id="expired_<?php echo $unique_id; ?>"></p>
                                <div class="countdowncontainer countdowncontainer_<?php echo $unique_id; ?>" style="display:none;">
                                    <span class="number-wrapper">
                                      <div class="line"></div>
                                      <span class="number day"><p id="countdown_days_<?php echo $unique_id; ?>">00</p></span>
                                      <div class="caption"><?php echo __('Days'); ?></div>
                                    </span>
                                    <span class="number-wrapper">
                                      <div class="line"></div>
                                      <span class="number hour"><p id="countdown_hours_<?php echo $unique_id; ?>">00</p></span>
                                      <div class="caption"><?php echo __('Hours'); ?></div>
                                    </span>
                                    <span class="number-wrapper">
                                      <div class="line"></div>
                                      <span class="number min"><p id="countdown_minutes_<?php echo $unique_id; ?>">00</p></span>
                                      <div class="caption"><?php echo __('Min'); ?></div>
                                    </span>
                                    <span class="number-wrapper">
                                      <div class="line"></div>
                                      <span class="number sec"><p id="countdown_seconds_<?php echo $unique_id; ?>">00</p></span>
                                      <div class="caption"><?php echo __('Sec'); ?></div>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>
                        <!-- Dailydeal Product End -->
                      <?php endif;?>
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <?php if($product_type == '13' || $product_type == '14' || $product_type == '19'  || $product_type == '20'): ?>
                          <?php echo $block->getProductDetailsHtml($_product); ?>
                        <?php endif;?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php echo $_product->getProductUrl() ?>">
                                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php if($_category_config['rating_star']): ?>
                        <?php
                            $review_html = $block->getReviewsSummaryHtml($_product, $templateType);
                        ?>
                        <?php if($review_html): ?>
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php else: ?>
                        <div class="product-reviews-summary short">
                            <div class="rating-summary">
                                <span class="label"><span>Rating:</span></span>
                                <div class="rating-result" title="0%">
                                    <span style="width:0"><span>0%</span></span>
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php endif; ?>

                        <?php if ($showDescription):?>
                            <div class="product description product-item-description">
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"
                                   class="action more"><?php echo __('Learn More') ?></a>
                            </div>
                        <?php endif; ?>
                        <?php if($_category_config['product_price']): ?>
                        <?php echo $block->getProductPrice($_product) ?>
                        <?php endif; ?>
                        <?php if($product_type != '13' && $product_type != '14' && $product_type != '19' && $product_type != '20'): ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                        <?php endif; ?>
                        <?php
                        $_product_show_actions = true;
                        $_product_details_inner_class = '';
                        if(in_array($product_type, ['3','5','6','7','8','9','11','13','14','17','19','20'])) {
                          $_product_show_actions = false;
                          if($product_type == '14' && $_button_pos =='outside'){
                            $_product_show_actions = true;
                            $_product_details_inner_class .= ' button-pos'.$_button_pos;
                          }
                          if($product_type == '14' && $_icon_only1 ) {
                            $_product_details_inner_class .= ' show-cart-icon';
                          }
                          if($product_type == '17' && ($_quantity_pos =='below' || $_quantity_pos =='above')){
                            $_product_show_actions = true;
                          }
                          if($product_type == '19' && ($_link_pos == 'default' || $_link_pos == 'top')){
                            $_product_show_actions = true;
                          }
                          if($product_type == '20' && $_box_style == 'box_full'){
                            $_product_show_actions = true;
                          }
                        }
                        if($_product_show_actions): ?>
                        <div class="product-item-inner<?=$_product_details_inner_class;?>">
                          <?php if($product_type == '20' && $_box_style == 'box_full'){?>
                            <div class="product description product-item-description">
                              <?php
                              $length = 118;
                              $shortContent = $_product->getShortDescription();
                              echo $shortContent = strip_tags((strlen($shortContent) > $length) ? substr($shortContent,0,$length).'...' : $shortContent);
                              ?>
                            </div>
                          <?php }?>
                            <div class="product actions product-item-actions<?php if(($product_type == '14' && $_button_pos == 'outside') || ($product_type == '20' && $_box_style == 'box_full')):?> d-flex align-items-center justify-content-center<?php endif;?>">
                                <?php if ($block->getMode() == 'grid'): ?>
                                <?php if($_category_config['addtowishlist'] && $product_type != '4'  && $product_type != '17' && $product_type != '19'): ?>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                    <a href="#"
                                       class="action towishlist actions-secondary"
                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button">
                                        <span><?php echo __('Add to Wish List') ?></span>
                                    </a>
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php endif; ?>
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post" class="d-flex flex-column flex-sm-row">
                                            <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php if($product_type == 10 || $product_type == 17):?>
                                                <div class="qty-box">
                                                    <a href="javascript:void(0)" class="qtyminus"><i class="porto-icon-minus"></i></a>
                                                    <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                                                    <a href="javascript:void(0)" class="qtyplus"><i class="porto-icon-plus"></i></a>
                                                </div>
                                            <?php endif;?>
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?php if ($block->getMode() == 'grid' && $product_type != '17' && $product_type != '19'): ?>
                                <?php if($_category_config['addtowishlist'] && $product_type == '4'): ?>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                    <a href="#"
                                       class="action towishlist actions-secondary"
                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button">
                                        <span><?php echo __('Add to Wish List') ?></span>
                                    </a>
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($block->getMode() == 'list'): ?>
                                <?php if($_category_config['addtowishlist']): ?>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                    <a href="#"
                                       class="action towishlist actions-secondary"
                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button">
                                        <span><?php echo __('Add to Wish List') ?></span>
                                    </a>
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php if($_category_config['addtocompare'] && $product_type != '17' && $product_type != '19'): ?>
                                <?php
                                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                ?>
                                <a href="#"
                                   class="action tocompare actions-secondary"
                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                   data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                   role="button">
                                    <span><?php echo __('Add to Compare') ?></span>
                                </a>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php endif; ?>
                    </div>
                    <?php endif;?>
                  </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php if(isset($_inscroll) && $_inscroll && isset($_inscrollAjax) && $_inscrollAjax):?>
    <div class="infinite-loader<?php if($_inscroll_mode == '2'):?> scrolling<?php endif; ?>"><a href="javascript:void(0)" class="loading" style="display: none;"><?php echo __("Loading ..."); ?></a><a href="javascript:void(0)" class="btn-load-more"><?php echo __("Load More ..."); ?></a></div>
    <?php endif;?>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
    <?php if ($block->getMode() == 'grid'): ?>
        <script type="text/javascript">
            require([
                'jquery'
            ], function ($) {
                <?php if($product_type == '20'){?>
                  window.setTimeout(function(){
                    $( '.product-item-info .effect-bhesfd' ).each( function() {
                        var $item = $( this ),
                            $detail = $item.find( '.product-item-details .product-item-inner' ),
                            height = $item.height() + $detail.height() + 32;
                        $item.find( '>.content-shadow' ).height( height );
                        $( window ).on( 'resize', function() {
                            $detail = $item.find( '.product-item-details .product-item-inner' );
                            height = $item.height() + $detail.height() + 32;
                            $item.find('>.content-shadow').height( height );
                        } );
                    });
                  },500);
                <?php }?>
                $('.main .products.grid .product-items li.product-item:nth-child(2n)').addClass('nth-child-2n');
                $('.main .products.grid .product-items li.product-item:nth-child(2n+1)').addClass('nth-child-2np1');
                $('.main .products.grid .product-items li.product-item:nth-child(3n)').addClass('nth-child-3n');
                $('.main .products.grid .product-items li.product-item:nth-child(3n+1)').addClass('nth-child-3np1');
                $('.main .products.grid .product-items li.product-item:nth-child(4n)').addClass('nth-child-4n');
                $('.main .products.grid .product-items li.product-item:nth-child(4n+1)').addClass('nth-child-4np1');
                $('.main .products.grid .product-items li.product-item:nth-child(5n)').addClass('nth-child-5n');
                $('.main .products.grid .product-items li.product-item:nth-child(5n+1)').addClass('nth-child-5np1');
                $('.main .products.grid .product-items li.product-item:nth-child(6n)').addClass('nth-child-6n');
                $('.main .products.grid .product-items li.product-item:nth-child(6n+1)').addClass('nth-child-6np1');
                $('.main .products.grid .product-items li.product-item:nth-child(7n)').addClass('nth-child-7n');
                $('.main .products.grid .product-items li.product-item:nth-child(7n+1)').addClass('nth-child-7np1');
                $('.main .products.grid .product-items li.product-item:nth-child(8n)').addClass('nth-child-8n');
                $('.main .products.grid .product-items li.product-item:nth-child(8n+1)').addClass('nth-child-8np1');
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
      var app = {
          isAppleDevice: function() {
            if (navigator.userAgent.match(/(iPhone|iPod|iPad|Safari)/) != null) {
              return true;
            }
            return false;
          }
      }
    // Timer for LEFT time for Dailydeal product
        var _second = 1000;
        var _minute = _second * 60;
        var _hour = _minute * 60;
        var _day = _hour * 24;
        var timer;

        //Set date as magentodatetime
        var date = new Date('<?php echo $_dailydealhelper->getcurrentDate() ?>');
        if (app.isAppleDevice()) {
          var mdate = '<?php echo $_dailydealhelper->getcurrentDate() ?>';
          var dateParts = mdate.substring(0,10).split('-');
          var timePart = mdate.substr(11);
          date = dateParts[1] + '/' + dateParts[2] + '/' + dateParts[0] + ' ' + timePart;
          date = new Date(date);
        }
        var l_date = new Date();
        var offset_date = l_date - date;

        function showRemaining()
        {
            $(".sw-dailydeal-wrapper").each(function(){
                var unique_id = $(this).attr("data-unique-id");
                // get Value of dailydeal product
                var cid='countdown_'+unique_id;
                var daysid='countdown_days_'+unique_id;
                var hoursid='countdown_hours_'+unique_id;
                var minutesid='countdown_minutes_'+unique_id;
                var secondsid='countdown_seconds_'+unique_id;

                var startdateid='fromdate_'+unique_id;
                var id='todate_'+unique_id;

                var enddate = new Date($('#'+id).val());
                var dealstartdate=new Date($('#'+startdateid).val());
                if (app.isAppleDevice() && $('#'+id).val() && $('#'+startdateid).val()) {
                  var ledate = $('#'+id).val();
                  var ledateParts = ledate.substring(0,10).split('-');
                  var letimePart = ledate.substr(11);
                  enddate = ledateParts[1] + '/' + ledateParts[2] + '/' + ledateParts[0] + ' ' + letimePart;
                  enddate = new Date(enddate).getTime();

                  var lsdate = $('#'+startdateid).val();
                  var lsdateParts = lsdate.substring(0,10).split('-');
                  var lstimePart = lsdate.substr(11);
                  dealstartdate = lsdateParts[1] + '/' + lsdateParts[2] + '/' + lsdateParts[0] + ' ' + lstimePart;
                  dealstartdate = new Date(dealstartdate).getTime();
                }
                var currentdate=new Date();

                //Get Difference between Two dates
                var distance = enddate - (currentdate - offset_date);

                $('.sw-dailydeal-wrapper').show();

                if (distance < 0) {
                   // clearInterval(timer);
                    $('#expired_'+unique_id).html("<span style='font-size:25px; color:#000;'>EXPIRED!<span>");

                } else if(dealstartdate > currentdate) {
                   $('.countdowncontainer_'+unique_id).hide();
                   var msg="<span style='font-size:15px; color:#000;'> Coming Soon..<br>Deal Start at:<br>"+$('#'+startdateid).val()+"<span>";
                   $('#expired_'+unique_id).html(msg);
                } else {
                    var days = Math.floor(distance / _day);
                    var hours = Math.floor((distance % _day) / _hour);
                    var minutes = Math.floor((distance % _hour) / _minute);
                    var seconds = Math.floor((distance % _minute) / _second);

                    if(hours < 10)
                        hours = "0" + hours;
                    if(minutes < 10)
                        minutes = "0" + minutes;
                    if(seconds < 10)
                        seconds = "0" + seconds;
                    $('.countdowncontainer_'+unique_id).show();
                    $('#'+daysid).html(days);
                    $('#'+hoursid).html(hours);
                    $('#'+minutesid).html(minutes);
                    $('#'+secondsid).html(seconds);
                }
            });
        }

        // Set Interval
        timer = setInterval(function()
        {
            showRemaining();
        }, 1000);
    });
    </script>
<?php
    echo $block->getChildHtml('filter_toggle');
?>
