<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/** @var $block \Webkul\Marketplace\Block\Product\Edit\Tab\Variations\Config */
use Webkul\Marketplace\Model\Product;

$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$productType = $block->getRequest()->getParam('type');
$filter = "configurable_associated_product_listing.configurable_associated_product_listing.listing_top.listing_filters";
$massAction = "configurable_associated_product_listing.configurable_associated_product_listing.product_columns.ids";
$columns = "configurable_associated_product_listing.configurable_associated_product_listing.product_columns";
if ($block->getSellerProduct()->getId()) {
    $productType = $block->getSellerProduct()->getTypeId();
}
$applicableProductType = [
    Product::PRODUCT_TYPE_SIMPLE,
    Product::PRODUCT_TYPE_CONFIGURABLE,
    Product::PRODUCT_TYPE_VIRTUAL
];
$isConfigurableProduct = $block->getSellerProduct()->getTypeId() === Product::PRODUCT_TYPE_CONFIGURABLE ||
 $block->getRequest()->has('attributes');
$allowedtypes=explode(',', $helper->getAllowedProductType());
if (in_array(Product::PRODUCT_TYPE_CONFIGURABLE, $allowedtypes) && in_array($productType, $applicableProductType)) { ?>
    <script>
        var BASE_URL = '';
        var FORM_KEY = "";
    </script>
    <div class="entry-edit form-inline" id="super_config" data-panel="product-variations">
        <div data-bind="scope: 'variation-steps-wizard'" class="product-create-configuration">
            <div class="product-create-configuration-info">
                <div class="note" data-role="product-create-configuration-info">
                    <?= $escaper
                    ->escapeHtml(__('Configurable products allow customers to choose options (Ex: shirt color).
                You need to create a simple product for each configuration (Ex: a product for each color).'));?>
                </div>
            </div>
            <div class="product-create-configuration-actions" data-action="product-create-configuration-buttons">
                <div class="product-create-configuration-action">
                    <button type="button" data-action="open-steps-wizard" 
                    title="<?= $escaper->escapeHtml(__('Create Product Configurations')) ?>"
                    class="action-secondary" data-bind="click: open">
                    <span data-role="button-label"
                    data-edit-label="<?=  $escaper->escapeHtml(__('Edit Configurations')) ?>">
                        <?= /* @escapeNotVerified */ $block->getSellerProduct()->getId() && $isConfigurableProduct
                            ? $escaper->escapeHtml(__('Edit Configurations'))
                            : $escaper->escapeHtml(__('Create Configurations'))
                        ?>
                    </span>
                    </button>
                </div>
            </div>
        </div>
        <div class="fieldset">
            <?= $block->getChildHtml('sellermatrix'); ?>

            <!-- Select Associated Product popup -->
            <div data-grid-id="associated-products-container">
                <div class="admin__data-grid-outer-wrap" 
                data-bind="scope: 'configurable_associated_product_listing.configurable_associated_product_listing'">
                    <div data-role="spinner" 
                    data-component=
                    "configurable_associated_product_listing.configurable_associated_product_listing.product_columns" 
                    class="admin__data-grid-loading-mask">
                        <div class="spinner">
                            <span></span><span></span><span></span>
                            <span></span><span></span><span></span><span></span><span></span>
                        </div>
                    </div>
                    <!-- ko template: getTemplate() --><!-- /ko -->

                </div>
            </div>

            <input type="hidden" name="affect_configurable_product_attributes" value="1" />
        </div>
    </div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "configurableProductGrid": {
                    "component": "Webkul_Marketplace/js/variations/product-grid",
                    "productsFilter": "<?= $escaper->escapeHtml($filter) ?>",
                    "productsProvider": "configurable_associated_product_listing.data_source",
                    "productsMassAction": "<?= $escaper->escapeHtml($massAction) ?>",
                    "productsColumns": "<?= $escaper->escapeHtml($columns) ?>",
                    "productsGridUrl": "<?= $escaper->escapeUrl($block
                    ->getUrl('marketplace/product/associated_grid', ['componentJson' => true,'_secure' => $block
                    ->getRequest()->isSecure()]))?>",
                    "configurableVariations": "configurableVariations"
                }
            }
        },
        "Webkul_Marketplace/js/configurable-type-handler": {
            "blockId": "#super_config",
            "tabId": "super_config",
            "hasVariations": "<?= $isConfigurableProduct ? 'true' : 'false' ?>"
        }
    }
}
</script>
    <?php
} ?>
