<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php
/**
 * @var \MageWorx\ReviewReminderBase\Block\Reminder\Email $block
 */
?>

<?php $reviews = $block->getReviews(); ?>

<?php if ($reviews): ?>
    <?php /** @var \Magento\Review\Model\Review $review */
    foreach ($block->getReviews() as $review): ?>
        <div class="mj-column-per-50 mj-outlook-group-fix div_9e058w">
            <table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
                <tbody>
                <tr>
                    <td class="td_i6a5a8">
                        <table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
                            <tr>
                                <td align="left" class="td_hn1xtp">
                                    <div class="div_a2njnd"><?= $block->escapeHtml($review->getNickname()) ?></div>
                                </td>
                            </tr>
                            <tr>
                                <td align="left" class="td_tqix0">
                                    <div class="div_57tk0v"><span class="span_j5wddk"><?= $block->escapeHtml(__('Feedback on:')) ?></span>
                                        <?= $block->escapeHtml($block->getProductName($review)) ?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td align="left" class="td_r9mtkf">
                                    <table border="0" cellpadding="0" cellspacing="0" role="presentation"
                                           class="table_fgh0fu">
                                        <tbody>
                                        <tr>
                                            <td class="td_e89jy7">
                                                <img alt="<?= $block->escapeHtml(__('Rating')) ?>"
                                                     height="15"
                                                     src="<?= $block->escapeHtmlAttr($block->getRatingImageUrlForReview($review)) ?>"
                                                     width="87"
                                                     class="img_yht6dz">
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td align="left" class="td_rb79fs">
                                    <div class="div_cnlc9">
                                        <?= $block->escapeHtml($block->getReviewDetail($review)) ?>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
