<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var MageWorx\XReviewBase\Block\Review\Customer\Product\Review $block */

$product = $block->getProductData();
?>
<?php if ($product->getId()) : ?>
    <div class="customer-review view">
        <div class="product-details">
            <div class="product-media">
                <a class="product-photo" href="<?= $block->escapeUrl($product->getProductUrl()) ?>">
                    <?php /* customer_account_product_review_page */ ?>
                    <?= $block->getImage($block->getProductData(), 'customer_account_product_review_page')->toHtml() ?>
                </a>
            </div>
            <div class="product-info">
                <h2 class="product-name"><?= $block->escapeHtml($product->getName()) ?></h2>
                <?php if ($block->getRating() && $block->getRating()->getSize()) : ?>
                    <span class="rating-average-label"><?= $block->escapeHtml(__('Average Customer Rating:')) ?></span>
                    <?= $block->getReviewsSummaryHtml($product) ?>
                <?php endif; ?>
            </div>
        </div>

        <div class="review-details">
            <?php if ($block->getRating() && $block->getRating()->getSize()) : ?>
                <div class="title">
                    <strong><?= $block->escapeHtml(__('Your Review')) ?></strong>
                </div>
                <div class="customer-review-rating">
                    <?php foreach ($block->getRating() as $_rating) : ?>
                        <?php if ($_rating->getPercent()) : ?>
                            <?php $rating = ceil($_rating->getPercent()) ?>
                            <div class="rating-summary item">
                                <span class="rating-label"><span><?= $block->escapeHtml($_rating->getRatingCode()) ?></span></span>
                                <div class="rating-result" title="<?= /* @noEscape */ $rating ?>%">
                                <span style="width:<?= /* @noEscape */ $rating ?>%">
                                    <span><?= /* @noEscape */ $rating ?>%</span>
                                </span>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
            <div class="review-title"><?= $block->escapeHtml($block->getReviewData()->getTitle()) ?></div>
            <div class="review-content"><?= /* @noEscape */ nl2br($block->escapeHtml($block->getReviewData()->getDetail())) ?></div>
            <?php if ($block->allowMediaGallery()): ?>
                <div class="mw-gallery mw-review__photos">

                    <?php foreach ($block->getReviewData()->getMediaGallery() as $mediaItem): ?>
                        <a class="mw-gallery__item"
                           href="<?= $block->escapeUrl($mediaItem->getMediaUrl()) ?>"
                           data-fslightbox="gallery"
                           data-thumb="<?= $block->escapeUrl($mediaItem->getThumbnailMediaUrl()) ?>">
                            <img src="<?= $block->escapeUrl($mediaItem->getThumbnailMediaUrl()) ?>"
                                 alt="<?= $block->escapeHtmlAttr($mediaItem->getLabel()) ?>"/>
                        </a>
                    <?php endforeach; ?>
                    <script type="text/x-magento-init">
                    {
                        "*": {
                            "xReviewGallery": {}
                        }
                    }
                    </script>
                </div>
            <?php endif; ?>
            <?php if ($block->isEnableProsAndCons()): ?>
                <div class="mw-grid review__pros-and-cons">
                    <div class="mw-grid__item mw-grid__item--half">
                        <div class="mw-pros"><?= /* @noEscape */
                            nl2br($block->escapeHtml($block->getReviewData()->getPros())) ?></div>
                    </div>
                    <div class="mw-grid__item mw-grid__item--half">
                        <div class="mw-cons"><?= /* @noEscape */
                            nl2br($block->escapeHtml($block->getReviewData()->getCons())) ?></div>
                    </div>
                </div>
            <?php endif; ?>
            <?php if ($block->isDisplayHelpful()): ?>
                <div class="mw-review__meta"
                     data-index="<?= (int)$block->getReviewData()->getId() ?>"
                     data-mage-init='{"vote":<?= /* @noEscape */ $block->getJsonVoteConfig() ?>}'>
                    <input type="hidden" name="form_key"
                           value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>"
                    />
                    <div class="mw-text mw-text--variation-subdued mw-review__meta-text">
                        <?= $block->escapeHtml(__('Review helpful?')) ?>
                    </div>
                    <div class="mw-rate mw-review__meta-rate-like">
                        <button class="mw-rate__icon" aria-label="Like">
                            <svg fill="currentColor" width="19" height="15" viewBox="0 0 19 19"
                                 xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                                <path
                                    d="m3.99998 9.54075-3.49998.00001v7.00004h3.49998m0-7.00005c.5-.66667 1.99983-1.99992 3-2.5.8-.4 1.66667-2.49993 2-3.99993 0-1 0-2 .5-2s2.50002-.500003 2.50002 2c0 2-.5 3-1 3.99993 1.1666-.16667 3.8-.4 5 0s1.5 1.5 1 2.5c.3333.49995 1 1.49995 0 2.49995.5 1 .5 2-.5 3 0 1 0 2-2 2.5-1.6.4-7.83335-.6665-10.50002-.9999m0-7.00005v7.00005"
                                    stroke="#000" stroke-linejoin="round"/>
                            </svg>
                        </button>
                        <div class="mw-rate__count">0</div>
                    </div>
                    <div class="mw-rate mw-review__meta-rate-dislike">
                        <button class="mw-rate__icon mw-rate__icon--dislike" aria-label="Dislike">
                            <svg fill="currentColor" height="15" viewBox="0 0 19 19" width="19"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="m3.99998 9.08846-3.499981-.00001v-7.00009l3.499981.00002m0 7.00008c.5.66667 1.99983 1.99994 3 2.50004.8.4 1.66667 2.4999 2 3.9999 0 1 0 2 .5 2s2.50002.5 2.50002-2c0-2-.5-3-1-3.9999 1.1666.1666 3.8.4 5 0s1.5-1.5 1-2.50004c.3333-.5 1-1.5 0-2.5.5-1 .5-2-.5-3 0-1 0-1.99999-2-2.49999-1.6-.400001-7.83336.66658-10.50002.99991m0 7.00008v-7.00008"
                                    stroke="#000" stroke-linejoin="round"/>
                            </svg>
                        </button>
                        <div class="mw-rate__count">0</div>
                    </div>
                </div>
            <?php endif; ?>
            <?php if ($block->getReviewData()->getAnswer()): ?>
                <div class="mw-review__reply">
                    <div class="mw-text mw-text--size-md mw-review__reply-heading">
                        <?= $block->escapeHtml(__('Brand reply')) ?>
                    </div>
                    <div class="mw-text mw-review__reply-content">
                        <?= /* @noEscape */ nl2br($block->escapeHtml($block->getReviewData()->getAnswer())) ?>
                    </div>
                </div>
            <?php endif; ?>
            <div class="review-date">
                <?= $block->escapeHtml(__('Submitted on %1', '<time class="date">' . $block->dateFormat($block->getReviewData()->getCreatedAt()) . '</time>'), ['time']) ?>
            </div>
        </div>
    </div>
    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back to My Reviews')) ?></span></a>
        </div>
    </div>
<?php endif; ?>
