<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \MageWorx\RewardPoints\Block\Product\RewardPromise $block */

?>
<?php if ($block->canBeDisplayed()): ?>
    <div id="mw-reward-promise" class="mwrp-banner" role="dialog" tabindex="-1" style="display: none"
         data-mage-init='{ "reward-promise": <?= /* @noEscape */ $block->getJsonConfig() ?> }'>
        <div id="mwrp-banner__content" class="mwrp-banner__content"></div>
    </div>
<?php endif; ?>
