<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$captchenable = $helper->getCaptchaEnable();
$partner = $block->getProfileDetail();
$sellerId = $partner->getSellerId();
?>
<div class="wk-mp-seller-profile-box wk-mp-collection-header-bottom-txt">
    <?php if ($helper->getSellerProfileLayout()==1):?>
        <a class="askque"><?= $escaper->escapeHtml(__('Contact')) ?></a>
    <?php else:?>
        <a class="askque"> <?= $escaper->escapeHtml(__('Contact Seller')) ?></a>
    <?php endif?>
    <div class="ask-que">
        <div id="wk-mp-ask-data">
            <div class="modals-wrapper">
                <aside tabindex="0" data-type="popup" data-role="modal" 
                class="modal-popup modal-slide _inner-scroll wk-mp-model-popup">
                    <div tabindex="0" data-role="focusable-start"></div>
                    <div data-role="focusable-scope" class="modal-inner-wrap">
                        <header class="modal-header">
                            <h4 class="modal-title"><?= $escaper->escapeHtml(__('Contact Seller')) ?></h4>
                            <button type="button" data-role="closeBtn" class="action-close wk-close">
                                <span><?= $escaper->escapeHtml(__('Close')) ?></span>
                            </button>
                            <span  class="wk-clear" ></span>
                        </header>
                        <?php
                        if ($helper->isCustomerLoggedIn()) {
                            $readonly = "readonly='readonly'";
                            $customer = $helper->getCustomerData();
                            $buyerName = $customer->getName();
                                $buyerEmail = $customer->getEmail();
                        } else {
                            $readonly = '';
                            $buyerName = '';
                            $buyerEmail = '';
                        }
                        ?>
                        <form id="ask-form" method="post" action="#" class="fieldset">
                            <div class="modal-body form-list field required">
                                <label class="label"><?= $escaper->escapeHtml(__('Your Name')) ?> :</label>
                                <input type="text" name="name" 
                                class="queryemail wk-contact_input_fields required-entry" 
                                value="<?= $escaper->escapeHtml($buyerName)?>" <?= /* @noEscape */ $readonly?>/>
                                <label class="label"><?= $escaper->escapeHtml(__('Your Email')) ?> :</label>
                                <input type="text" name="email" 
                                class="queryemail required-entry validate-email wk-contact_input_fields" 
                                value="<?= $escaper->escapeHtml($buyerEmail)?>" <?= /* @noEscape */ $readonly?>/>
                                <label class="label"><?= $escaper->escapeHtml(__('Subject')) ?> :</label>
                                <input type="text" name="subject" class="wk-contact_input_fields required-entry"/>
                                <label class="label"><?= $escaper->escapeHtml(__('Your Query')) ?> :</label>
                                <textarea  name="ask" 
                                class="wk-full-width queryquestion wk-contact_input_fields required-entry"></textarea>
                                <input type="hidden" name="seller-id" value="<?= $escaper->escapeHtml($sellerId);?>"/>
                                <?php if ($captchenable) { ?>
                                    <label class="label">
                                        <?= $escaper->escapeHtml(__('Please enter desired result')) ?></label>
                                    <div>
                                        <span>
                                            <label for="wk-mp-captcha"><span id="wk-mp-captchalable1">
                                                <?= $escaper->escapeHtml(rand(1, 20))?></span> + 
                                                <span id="wk-mp-captchalable2">
                                                    <?= $escaper->escapeHtml(rand(1, 20))?></span> =</label>
                                        </span>
                                        <input type="text" class="required-entry wk-contact_input_fields" 
                                        name="wk-mp-captcha" id="wk-mp-captcha" />
                                    </div>
                                    <?php
                                }?>
                            </div>
                            <div class="modal-footer">
                                <span class="error"></span>
                                <span class="errormail"></span>
                                <input type="reset" value="<?= $escaper->escapeHtml(__('Reset')) ?>"
                                 id="resetbtn" class="wk-btn wk-btn_default"/>
                                <input type="submit" value="<?= $escaper->escapeHtml(__('Submit')) ?>"
                                 id="askbtn" class="wk-btn wk-btn-primary clickask"/>
                                <span class="wk-clear"></span>
                            </div>
                        </form>
                    </div>
                    <div tabindex="0" data-role="focusable-end"></div>
                </aside>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "sellerProfileContact": {
                "wrongNumber": "<?= $escaper->escapeHtml(__(' Wrong verification number. ')) ?>",
                "mailUrl": "<?= $escaper->escapeUrl($block
                                        ->getUrl("marketplace/seller/sendmail", ["_secure" => $block
                                        ->getRequest()->isSecure()])) ?>",
                "mailSent": "<?= $escaper->escapeHtml(__('Your mail has been sent.')) ?>",
                "captchenable": <?= $escaper->escapeHtml($captchenable) ?>
            }
        }
    }
</script>