<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$helperOrders = $viewModel->getOrderHelper();
$partner = $block->getProfileDetail();
$reportMsg = "We will re-verify the seller Information and see if it violates any of our policy or selling guidelines.";
$currentUrl = $escaper->escapeUrl($block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]));
$companyDesc = $block->stripTags($block->getFilterData($partner['company_description']));
if ($partner['shop_url']):
    $bannerpic = $partner->getBannerPic()!=''?$partner->getBannerPic():$helper->getProfileBannerImage();
    $bannerpic = $helper->getMediaUrl().'avatar/'.$bannerpic;

    $logo = $partner->getLogoPic()!=''?$partner->getLogoPic():"noimage.png";
    $logo = $helper->getMediaUrl().'avatar/'.$logo;
    $sizeArr = $helper->getImageSize($logo);
    if (!empty($sizeArr) && !empty($sizeArr['width']) && !empty($sizeArr['height'])) {
        $width = $sizeArr['width'];
        $height = $sizeArr['height'];
        $calculatedHeight = 80;
        $calculatedWidth = ($width / $height) * $calculatedHeight;
        $calculatedPercent = ($width / $height) * 2.5;
        if ($calculatedHeight) { ?>
            <style>
                .wk-mp-collection-seller-title-container {
                    padding-left: calc(<?= $escaper->escapeHtml($calculatedPercent) ?>% + 
                    <?= $escaper->escapeHtml($calculatedWidth) ?>px);
                }
            </style>
            <?php
        }
    }
    $shopUrl = $escaper->escapeHtml($partner['shop_url']);
    $shoptitle = $escaper->escapeHtml($partner->getShopTitle());
    if (!$shoptitle) {
        $shoptitle = $shopUrl;
    }
    $sellerId = $partner->getSellerId();
    $locsearch = $escaper->escapeHtml($partner['company_locality']);
    $sellerProductCount = $helper->getSellerProCount($sellerId);
    $flagReasons = $block->getSellerFlagReasons();
    if ($helper->getActiveColorPicker()):?>
        <style>
            .marketplace-seller-collection .wk-mp-collection-product-count-container,
            .marketplace-seller-profile .wk-mp-collection-product-count-container,
            .marketplace-seller-feedback .wk-mp-collection-rating-count-container {
                border-bottom-color: <?= $escaper->escapeHtml($partner['background_width']);?>;
            }
        </style>
    <?php endif ?>
    <?php  // starting of the div ?>
    <div class="wk-mp-header-layout2">
        <div class="wk-mp-header-container">
            <div class="wk-mp-header-container-left">
                
                <a href="<?=
                            $escaper->escapeUrl(
                                $helper->getRewriteUrl('marketplace/seller/profile/shop/'.$shopUrl)
                            );?>" >
                    <img class="wk-mp-collection-logo" src="<?= $escaper->escapeUrl($logo);?>" />
                </a>
                <div class="wk-mp-left-seller-content">
                    <div>
                        <a href="<?= $escaper->escapeUrl($helper
                        ->getRewriteUrl('marketplace/seller/profile/shop/'.$shopUrl));?>"
                            class="wk-mp-layout2-seller-title">
                            <?= $escaper->escapeHtml($shoptitle)?>
                        </a>
                    </div>
                    <div class="description">
                        <?php if (strlen($companyDesc) >= 200) {
                                $companyShortDesc = substr($companyDesc, 0, 200)."...";
                            ?>
                            <?= $escaper->escapeHtml($companyShortDesc);?>
                            <span class="read-more"><?= $escaper->escapeHtml(__("Read More"));?></span>
                            <?php
                        } else {?>
                            <?= $escaper->escapeHtml($companyDesc);?>
                        <?php } ?>
                    </div>
                    <div class="shop-info">
                        <?php if ($locsearch) { ?>
                            <div>
                                <a title="<?= $escaper->escapeHtml(__('Search')) ?>"
                                href="<?=
                                        $escaper->escapeUrl(
                                            $helper->getRewriteUrl('marketplace/seller/location/shop/'.$shopUrl)
                                            ."?loc=".$locsearch
                                        )?>" target="_blank" class="location-icon">
                                        <?= $escaper->escapeHtml(__($locsearch)); ?>
                                </a>
                            </div>
                        <?php } ?>
                        <div>
                            <a href="#" class="rating-icon">
                                <?= $escaper->escapeHtml($helper->getSelleRating($sellerId)); ?>
                                <?= $escaper->escapeHtml(__('Rating'))?>
                            </a>
                        </div>
                        <?php if ($helper->getSellerFlagStatus() && (
                        ($flagReasons->getSize() && $helper->getSellerFlagData('reason')) ||
                        $helper->getSellerFlagData('other_reason'))
                        ) { ?>
                            <span class="wk-report-seller">
                                <a id="reportflag" class="flag-icon">
                                    <?= $escaper->escapeHtml($helper->getSellerFlagData('seller_flag_label')) ?>
                                </a>
                            </span>
                        <?php } ?>
                        <div class="wk-mp-layout2-social-media">
                            <?php if ($partner->getFbActive()) { ?>
                            <div>
                                <a href="//facebook.com/<?= $escaper->escapeHtml($partner->getFacebookId());?>"
                                target="_blank">
                                    <span class="wk-mp-profile-icon-css wk-mp-profile-icon-fb" 
                                    title="<?= $escaper->escapeHtml(__('Check in Facebook'))?>"></span>
                                </a>
                            </div>
                            <?php }
                            if ($partner->getTwActive()) { ?>
                                <div>
                                    <a href="//twitter.com/<?= $escaper->escapeHtml($partner->getTwitterId());?>"
                                    target="_blank">
                                        <span class="wk-mp-profile-icon-css wk-mp-profile-icon-tw" 
                                        title="<?= $escaper->escapeHtml(__('Check in Twitter'))?>"></span>
                                    </a>
                                </div>
                                <?php
                            }
                            if ($partner->getVimeoActive()) { ?>
                                <div>
                                    <a href="//vimeo.com/<?= $escaper->escapeHtml($partner->getVimeoId());?>"
                                    target="_blank">
                                        <span class="wk-mp-profile-icon-css wk-mp-profile-icon-vimeo" 
                                        title="<?= $escaper->escapeHtml(__('Check in Vimeo'))?>"></span>
                                    </a>
                                </div>
                                <?php
                            }
                            if ($partner->getYoutubeActive()) { ?>
                                <div>
                                    <a href="//www.youtube.com/c/<?= $escaper->escapeHtml($partner->getYoutubeId());?>"
                                    target="_blank">
                                        <span class="wk-mp-profile-icon-css wk-mp-profile-icon-youtube" 
                                        title="<?= $escaper->escapeHtml(__('Check in Youtube'))?>"></span>
                                    </a>
                                </div>
                                <?php
                            }
                            if ($partner->getInstagramActive()) { ?>
                                <div>
                                   <a href="//www.instagram.com/<?= $escaper->escapeHtml($partner->getInstagramId());?>"
                                    target="_blank">
                                        <span class="wk-mp-profile-icon-css wk-mp-profile-icon-instagram" 
                                        title="<?= $escaper->escapeHtml(__('Check in Instagram'))?>"></span>
                                    </a>
                                </div>
                                <?php
                            }
                            if ($partner->getPinterestActive()) { ?>
                                <div>
                                   <a href="//www.pinterest.com/<?= $escaper->escapeHtml($partner->getPinterestId());?>"
                                    target="_blank">
                                        <span class="wk-mp-profile-icon-css wk-mp-profile-icon-pinterest" 
                                        title="<?= $escaper->escapeHtml(__('Check in Pinterest'))?>"></span>
                                    </a>
                                </div>
                                <?php
                            } ?>
                        </div>
                        <?= $block->getChildHtml('seller_badges_top') ?>
                        <?= $block->getChildHtml("marketplace_seller_profile_contact")?>
                    </div>
                    
                </div>
            </div>
            <div class="wk-mp-header-container-right">
                <?php if ($helper->isSellerSliderModuleInstalled()) { ?>
                    <?= $block->getChildHtml("marketplace_seller_slider_block");
                } ?>
                <img class="wk-mp-banner-image" src="<?= $escaper->escapeHtml($bannerpic); ?>">
            </div>
        </div>
    </div>
<?php endif ?>
<?php if ($helper->getSellerFlagStatus()): ?>
      <div class="seller-flag">
          <div id="wk-mp-flag-data">
              <div class="wk-mp-modals-wrapper">
                  <aside tabindex="0" data-type="popup" data-role="modal" 
                  class="modal-popup modal-slide _inner-scroll wk-mp-model-flag-popup">
                      <div tabindex="0" data-role="focusable-start"></div>
                      <div data-role="focusable-scope" class="modal-inner-wrap">
                          <header class="modal-header">
                              <h4 class="modal-title">
                                <?= $escaper->escapeHtml($helper->getSellerFlagData('seller_flag_label')) ?></h4>
                              <button type="button" data-role="closeBtn" class="action-close wk-seller-flag-close">
                                  <span><?= $escaper->escapeHtml(__('Close'))?></span>
                              </button>
                              <span class="wk-seller-flag-clear"></span>
                          </header>
                          <?php
                            if ($helper->isCustomerLoggedIn()) {
                                $readonly = "readonly='readonly'";
                                $customer = $helper->getCustomerData();
                                $reporterName = $customer->getName();
                                $reporterEmail = $customer->getEmail();
                            } else {
                                $readonly = '';
                                $reporterName = '';
                                $reporterEmail = '';
                            }
                            ?>
                          <form id="flag-form" method="post" action="#" class="fieldset">
                              <div class="modal-body form-list wk-flag-form field required">
                                  <label class="label"><?= $escaper->escapeHtml(__('Your Name')) ?> :</label>
                                  <input type="text" name="name" 
                                  class="queryemail wk-contact_input_fields required-entry" 
                                  value="<?= $escaper->escapeHtml($reporterName)?>" <?= /* @noEscape */ $readonly?>/>
                                  <label class="label"><?= $escaper->escapeHtml(__('Your Email')) ?> :</label>
                                  <input type="text" name="email" 
                                  class="queryemail required-entry validate-email wk-contact_input_fields" 
                                  value="<?= $escaper->escapeHtml($reporterEmail)?>" <?= /* @noEscape */ $readonly?>/>
                                  <?php if ($helper->getProductFlagData('reason')):
                                        ?>
                                    <label class="label"><?= $escaper
                                    ->escapeHtml(__('Choose an appropriate reason to flag')) ?>
                                     :</label>
                                        <?php foreach ($flagReasons as $flagReason): ?>
                                      <div class="wk-flagreasons">
                                        <input type="radio" name="reason" 
                                        id="<?= $escaper->escapeHtml($flagReason->getId()) ?>" 
                                        class="flag-reason required-entry" 
                                        value="<?= $escaper->escapeHtml($flagReason->getReason())?>" >
                                        <label for="<?=$escaper->escapeHtml($flagReason->getId()) ?>">
                                            <?= $escaper->escapeHtml($flagReason->getReason()) ?></label>
                                      </div>
                                    <?php endforeach; ?>
                                        <?php if ($helper->getProductFlagData('other_reason')): ?>
                                      <div class="wk-flagreasons">
                                        <input type="radio" name="reason" id="reason_other"
                                        class="flag-reason required-entry" value="other_value" checked>
                                        <label for="reason_other">
                                            <?=
                                                $escaper->escapeHtml(
                                                    $helper->getProductFlagData('other_reason_label')
                                                ) ?>
                                        </label>
                                      </div>
                                      <textarea name="flag_other_reason" 
                                      placeholder="<?= $escaper->escapeHtml(__("Write a reason to flag this seller"))?>"
                                       class="wk-full-width wk-flag-other-reason required-entry"></textarea>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                  <input type="hidden" name="seller_id" 
                                  value="<?= $escaper->escapeHtml($sellerId);?>"/>
                                  <input type="hidden" name="seller_name" 
                                  value="<?= $escaper->escapeHtml($shoptitle);?>" />
                              </div>
                              <div class="modal-footer">
                                  <span class="error"></span>
                                  <span class="errormail"></span>
                                  <input type="reset" value="<?= $escaper->escapeHtml(__('Reset')) ?>"
                                   id="resetflagbtn" class="wk-btn wk-btn-seller-flag_default"/>
                                  <input type="submit" value="<?= $escaper->escapeHtml(__('Submit')) ?>"
                                   id="flagbtn" class="wk-btn wk-btn-seller-flag-primary clickflag"/>
                                  <span class="wk-seller-flag-clear"></span>
                              </div>
                          </form>
                      </div>
                      <div tabindex="0" data-role="focusable-end"></div>
                  </aside>
              </div>
          </div>
      </div>
      <div class="wk-alert-modal-content">
        <div class="wk-flag-status-content">
            <p>
                <?= $escaper->escapeHtml(__('Thank you.'))?>
            </p>
            <p>
                <?= $escaper->escapeHtml(__('Your report against '))?>
                <b>
                    <?= $escaper->escapeHtml($shoptitle);?>
                </b>
                <?= $escaper->escapeHtml(__(' has been submitted.'))?>
            </p>
            <p>
                <?= $escaper->escapeHtml(__($reportMsg))?>
            </p>
        </div>
      </div>
    <?php endif;?>
<script type="text/x-magento-init">
    {
        "*": {
            "sellerProfileReport": {
                "sellerReportUrl": "<?= $escaper->escapeUrl(
                    $block->getUrl(
                        "marketplace/seller/reportflag",
                        ["_secure" => $block->getRequest()->isSecure()]
                    )
                ) ?>"
            }
        }
    }
</script>