<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$pageLayout  =    $helper->getSellerProfileLayout();
if ($pageLayout == 1): ?>
    <?= $block->getChildHtml('marketplace_seller_top_block_layout1'); ?>
<?php elseif ($pageLayout == 2): ?>
    <?= $block->getChildHtml('marketplace_seller_top_block_layout2'); ?>
<?php endif; ?>
