<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $partner = $block->getProfileDetail();
?>
<?php if (!empty($partner['shop_url'])): ?>
    <div class="wk-mp-design">
        <?= $block->getChildHtml();?>
    </div>
<?php endif; ?>
