<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$profile_hint_status = $helper->getProfileHintStatus();
$imgPath = 'Webkul_Marketplace::images/quest.png';
?>
<div class="field required" id="wantptr">
    <label for="wantpartner" class="label"><?= $escaper->escapeHtml(__('Do You Want To Become A Seller / Vendor?')) ?>
    </label>
    <?php
    if ($profile_hint_status && $helper->getProfileHintBecomeSeller()) {?>
        <img src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>" 
        class='questimg' title="<?= $escaper->escapeHtml($helper->getProfileHintBecomeSeller()) ?>"/>
        <?php
    }?>
    <div class="control">
        <input type="radio" id="wantpartner" class="wantpartner" name="is_seller" 
        value='1' title="<?= $escaper->escapeHtml(__('Agree as Seller')) ?>"  /> 
        <?= $escaper->escapeHtml(__("Yes")); ?>&nbsp;&nbsp;
        <input type="radio" id="wantpartner0" class="wantpartner" name="is_seller" 
        value='0' title="<?= $escaper->escapeHtml(__('Disagree as Seller')) ?>" 
        checked /> <?= $escaper->escapeHtml(__("No")); ?>
    </div>
</div>
<div id="seller-shop-field-wrapper">
    <script id="wantptr-template" type="text/x-magento-template">
        <div id="<%- data.id %>" class="profileurl field required">
            <label class="label">
                <%- data.label %>
                <?php
                if ($helper->getProfileHintStatus() && $helper->getProfileHintShopurl()) {?>
                    <img
                    src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl($imgPath));?>" 
                    class='questimg' title="<?= $escaper->escapeHtmlAttr($helper->getProfileHintShopurl())?>"/>
                    <?php
                } ?>
            </label>
            <div class="control" id="wk-mp-become-seller-box-wrapper" data-role="wk-mp-become-seller-box-wrapper">
                <input type="text" class="input-text required-entry" 
                name="profileurl" maxlength="50" id="profileurl" data-role="shop-url" 
                placeholder="<%- data.title %>" title="<%- data.title %>" value=""/>
                <div id="wk-load" class="no-display">
                    <img height="16px" width="16px" src="<%- data.src %>" />
                </div>
                <span class="required-entry" type="text">
                    <%- data.text %>
                </span>
            </div>
            <div id="wk-load" class="no-display">
                <img height="16px" width="16px" src="<%- data.src %>" />
            </div>
        </div>
    </script>
</div>
<?php
$shopurl_hint = '';
if ($profile_hint_status && $helper->getProfileHintShopurl()) {
    $shopurl_hint = '<img src="'.$block->getViewFileUrl('Webkul_Marketplace::images/quest.png').'" 
    class="questimg" title="'.$helper->getProfileHintShopurl().'"/>';

} else {
    $shopurl_hint = '';
} ?>

<?php
$formData = [
    'ajaxSaveUrl' => $block->getUrl("marketplace/seller/usernameverify", ["_secure" => $block
    ->getRequest()->isSecure()]),
    'successMessage' => __("Congratulations! Shop name is available."),
    'errorMessage' => __("Sorry! But this shop name is not available, please set another shop name."),
    'loaderImage' => $block->getViewFileUrl('Webkul_Marketplace::images/ajax-loader-tr.gif'),
    'button' => 'button.submit'
];
$serializedFormData = $viewModel->getJsonHelper()->jsonEncode($formData);
?>

<script type="text/x-magento-init">
    {
        "#form-validate": {
            "verifySellerShop": <?= /* @noEscape */ $serializedFormData; ?>
        }
    }
</script>
