<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $paramData = $block->getRequest()->getParams();
if (empty($paramData['loc'])) {
    $viewModel = $block->getViewModel();
    $helper = $viewModel->getHelper();
    $partner = $block->getProfileDetail();
    $locsearch = $partner['company_locality'];
    $paramData['loc'] = $locsearch;
}
?>
<div class="wk_mp_design">
    <?= $block->getChildHtml("marketplace_seller_top_block")?>
    <div class="wk-mp-collection-container">
        <iframe width="100%" height="550" frameborder="0"
        scrolling="no" marginheight="0" marginwidth="0" 
        src="//maps.google.com/maps?q=<?= /* @noEscape */$paramData['loc'];?>&amp;output=embed"></iframe>
        <br />
        <small>
            <a href="//maps.google.com/maps?q=<?= $escaper->escapeHtml($paramData['loc']);?>" 
            class="wk_loc_inf"><?= $escaper->escapeHtml(__('View Larger Map')) ?></a>
        </small>
    </div>
</div>
