<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/** @var $block \Webkul\Marketplace\Block\Product\Configurableattribute */
$attributeId = $block->getRequest()->getParam('attribute_id');
$attributeData = [];
$attributeOptions = [];
$defaultValue = 0;
$storeOptions =[];
$backUrl = $block->getUrl('marketplace/product_attribute/new');
if (!empty($attributeId)) {
    $attributeData = $block->getEditAttributeData($attributeId);
    $attributeCode = $attributeData['attribute_code'];
    $attributeLabel = $attributeData['attribute_label'];
    $frontendInput = $attributeData['frontend_input'];
    $valRequired = $attributeData['val_required'];
    $defaultValue = !empty($attributeData['default_value'])?$attributeData['default_value']:0;
    $storeOptions = $attributeData['store_options'];
    $attributeOptions = $attributeData['options'];
}
?>
<form action="<?= $escaper->escapeUrl($block
->getUrl('marketplace/product_attribute/save', ['_secure' => $block->getRequest()->isSecure()])) ?>"
 method="POST"  id="form-customer-attr-new" data-mage-init='{"validation":{}}'>
    <div class="wk-mp-design">
        <fieldset class="info wk-mp-fieldset fieldset" id="associate-product">
            <legend class="legend">
                <span><?= $escaper->escapeHtml(__('Create Attribute for Configurable Products')) ?></span>
                <?php if (!empty($attributeId)) {?>
                <button 
                 class="button wk-mp-btn wk-cnfig-back">
                    <span><span><?= $escaper->escapeHtml(__('Back')) ?></span></span>
                </button>
                <?php  } ?>
                <button type="reset" class="button wk-mp-btn">
                    <span><span><?= $escaper->escapeHtml(__('Reset')) ?></span></span>
                </button>
                <button class="button wk-mp-btn" title="<?= $escaper->escapeHtml(__('Save')) ?>"
                 type="submit" id="save-btn">
                    <span><span><?= $escaper->escapeHtml(__('Save Attribute')) ?></span></span>
                </button>
            </legend>
            <?= $block->getBlockHtml('seller.formkey')?>
            <?= $block->getBlockHtml('formkey')?>

            <div class="fieldset form-list" id="cust">

                <div class="field required">
                    <label class="label"><?= $escaper->escapeHtml(__('Attribute Code')) ?> : </label>
                    <div class="control">
                        <input type="text" 
                        class="validate-code validate-length maximum-length-30 input-text required-entry" 
                        name="attribute_code" id="" 
                        value="<?= $escaper->escapeHtml(isset($attributeCode) ? $attributeCode:"")?>" />
                    </div>
                </div>
                <div class="field required">
                    <label class="label"><?= $escaper->escapeHtml(__('Attribute Label')) ?> : </label>
                    <div class="control">
                        <input type="text" class="required-entry widthinput input-text" 
                        name="attribute_label" id=""
                         value="<?=  $escaper->escapeHtml(isset($attributeLabel) ? $attributeLabel:"")?>"/>
                    </div>
                </div>
                <div class="field required">
                    <label class="label"><?= $escaper->escapeHtml(__('Catalog Input Type')) ?> : </label>
                    <div class="control">
                        <select id="frontend_input" class=" select validate-select"
                         title="<?= $escaper->escapeHtml(__('Catalog Input Type for Store Owner')) ?>"
                          name="frontend_input">
                            <option value=""><?= $escaper->escapeHtml(__("Please Select")); ?></option>
                            <option value="select" <?= isset($frontendInput) && $frontendInput == "select" ?
                             "selected":""?>><?= $escaper->escapeHtml(__("Dropdown")); ?></option>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <label class="label"><?= $escaper->escapeHtml(__('Values Required')) ?> : </label>
                    <div class="control">
                        <select id="val_required" class="select val_required" 
                        title="<?= $escaper->escapeHtml(__('Values Required')) ?>" name="val_required">
                            <option value="1" <?= isset($valRequired) && $valRequired == 1 ? "selected":""?>
                            ><?= $escaper->escapeHtml(__("Yes")); ?></option>
                            <option <?= isset($valRequired) && $valRequired == 0 ? "selected":""?>
                             value="0"><?= $escaper->escapeHtml(__("No")); ?>
                        </option>
                        </select>
                    </div>
                </div>
                <input type="hidden" name="attribute_id" value="<?= $escaper->escapeHtml($attributeId)?>"/>
                <?= $block->getChildHtml() ?>
            </div>
        </fieldset>
    </div>
</form>
<div class="buttons-set">
    <p class="back-link">
        <a href="javascript:;" onclick="javascript: window.history.back();" 
        class="left">&laquo; <?= $escaper->escapeHtml(__('Back')) ?></a>
    </p>
</div>
<?php
$serializedFormData = $block->getJsonHelper()->jsonEncode($attributeOptions);
$storeOptions = $block->getJsonHelper()->jsonEncode($storeOptions);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "sellerCreateConfigurable": {
                "attributeOptions" : <?=  /* @noEscape */ $serializedFormData;?>,
                "storeOptions" : <?=  /* @noEscape */ $storeOptions;?>,
                "defaultValue" : <?=  /* @noEscape */ $defaultValue;?>,
                "backUrl" : "<?=  /* @noEscape */ $backUrl;?>"
            }
        }
    }
</script>
