<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$product_id=$block->getRequest()->getParam('id');
$getValues = $block->getGoogleoptimizerFieldsValues();
?>
<input type="hidden" name="google_experiment[experiment_script]" 
value="<?= $escaper->escapeHtmlAttr($getValues['experiment_script'])?>">
<input type="hidden" name="google_experiment[code_id]" value="<?= $escaper->escapeHtmlAttr($getValues['code_id'])?>">
