<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$name = $block->getNameInLayout();
foreach ($block->getChildNames($name) as $childName): ?>
    <?= $block->getChildBlock($childName)->setItem($block->getItem())->toHtml(); ?>
<?php endforeach; ?>
