<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$orderHelper = $viewModel->getOrderHelper();
$isPartner = $helper->isSeller();
if ($isPartner == 1) {
    $order_id = $block->getRequest()->getParam('order_id');

    $creditmemo_id = $block->getRequest()->getParam('creditmemo_id');

    $order = $block->getOrder();

    $creditmemo = $block->getCreditmemo();

    $paymentCode = '';
    $payment_method = '';
    if ($order->getPayment()) {
        $paymentCode = $order->getPayment()->getMethod();
        $payment_method = $order->getPayment()->getMethodInstance()->getTitle();
    }
    $creditmemo_status = '';
    if ($creditmemo->getState()==1) {
        $creditmemo_status = __('Pending');
    } elseif ($creditmemo->getState()==2) {
        $creditmemo_status = __('Refunded');
    } elseif ($creditmemo->getState()==3) {
        $creditmemo_status = __('Canceled');
    }
    $marketplace_orders = $block->getSellerOrderInfo($order_id);
    if (count($marketplace_orders)) {    ?>
        <div class="wk-mp-design">
            <div class="fieldset wk-mp-fieldset">
                <div class="page-title-wrapper">
                    <h1 class="page-title">
                        <span data-ui-id="page-title-wrapper" class="base">
                            <?= $escaper->escapeHtml(__('Creditmemo #%1', $creditmemo->getIncrementId())) ?>
                        </span>
                    </h1>
                    <span class="order-status"><?= $escaper->escapeHtml($creditmemo_status)?></span>
                    <?php
                    $date = $block->formatDate(
                        $creditmemo->getCreatedAt(),
                        \IntlDateFormatter::MEDIUM,
                        true,
                        $block->getTimezoneForStore($order->getStore())
                    );
                    $orderDate = __(
                        '<span class="label">Order Date:</span> %1',
                        '<date>' . $date . '</date>'
                    );
                    $url = $block->getUrl(
                        'marketplace/order_creditmemo/email',
                        [
                            'order_id' => $order_id,
                            'creditmemo_id' => $creditmemo_id,
                            '_secure' => $block->getRequest()->isSecure()
                        ]
                    );
                    $confMsg = __("Are you sure you want to send credit memo email to customer?");
                    ?>
                    <div class="order-date">
                        <?= /* @noEscape */ $orderDate?>
                    </div>
                    <div class="actions-toolbar order-actions-toolbar">
                        <div class="actions">
                            <a href="<?= $escaper->escapeUrl($url)?>" 
                                onclick="return confirm('<?= /* @noEscape */ $confMsg?>')" 
                                class="action">
                                <button class="button wk-mp-btn"
                                title="<?= $escaper->escapeHtml(__('Send Email To Customer')) ?>"
                                type="button">
                                    <span><span><?= $escaper->escapeHtml(__('Send Email')) ?></span></span>
                                </button>
                            </a>
                            <a href="<?= $escaper->escapeUrl($block
                            ->getUrl(
                                'marketplace/order_creditmemo/printpdf',
                                ['order_id'=>$order_id,'creditmemo_id'=>$creditmemo_id,
                                '_secure' => $block->getRequest()->isSecure()]
                            ));?>" class="action">
                                <button class="button wk-mp-btn" title="<?= $escaper->escapeHtml(__('Print')) ?>">
                                    <span><span><?= $escaper->escapeHtml(__('Print')) ?></span></span>
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="block block-order-details-view">
                    <div class="block-title">
                        <strong><?= $escaper->escapeHtml(__('Order Information')) ?></strong>
                    </div>
                    <div class="block-content">
                        <div class="box-content">
                            <div class="box wk-box">
                                <strong class="box-title wk-order-info-title">
                                    <a href="<?= $escaper->escapeUrl($block
                                    ->getUrl('marketplace/order/view', ['id'=>$order_id, '_secure' => $block
                                    ->getRequest()->isSecure()]));?>">
                                        <?= $escaper->escapeHtml(__('Order # %1', $order->getIncrementId())) ?>
                                    </a>
                                </strong>
                                <div class="box-content">
                                    <div class="wk-row">
                                        <span class="label"><?= $escaper->escapeHtml(__('Order Status'))?> : </span>
                                        <span class="value">
                                            <?= $escaper->escapeHtml(strtoupper(__($order->getStatus()))); ?></span>
                                    </div>
                                    <div class="wk-row">
                                        <span class="label"><?= $escaper->escapeHtml(__('Order Date'))?> : </span>
                                        <span class="value">
                                            <?= /* @noEscape */ $block->formatDate($order
                                            ->getCreatedAt(), \IntlDateFormatter::MEDIUM, true, $block
                                            ->getTimezoneForStore($order->getStore())); ?></span>
                                    </div>
                                </div>
                            </div>
                            <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                                <div class="box wk-box">
                                    <strong class="box-title"><span>
                                        <?= $escaper->escapeHtml(__('Buyer Information')) ?></span></strong>
                                    <div class="box-content">
                                        <div class="box wk-box">
                                            <div class="wk-row">
                                                <span class="label">
                                                    <?= $escaper->escapeHtml(__('Customer Name'))?> : 
                                                </span>
                                                <span class="value">
                                                    <?= $escaper->escapeHtml($order->getCustomerName()); ?></span>
                                            </div>
                                            <div class="wk-row">
                                                <span class="label"><?= $escaper->escapeHtml(__('Email'))?> : </span>
                                                <span class="value">
                                                    <?= $escaper->escapeHtml($order->getCustomerEmail()); ?></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                    <div class="block block-order-details-view">
                        <div class="block-title">
                            <strong><?= $escaper->escapeHtml(__('Address Information')) ?></strong>
                        </div>
                        <div class="block-content">
                            <div class="box-content">
                                <div class="box box-order-billing-address wk-box">
                                    <strong class="box-title">
                                        <span><?= $escaper->escapeHtml(__('Billing Address')) ?></span>
                                    </strong>
                                    <div class="box-content">
                                        <address><?= /* @noEscape */
                                         $block->getFormattedAddress($order->getBillingAddress()); ?></address>
                                    </div>
                                </div>
                                <?php if ($block->isOrderCanShip($order)): ?>
                                    <div class="box box-order-shipping-address wk-box">
                                        <strong class="box-title">
                                            <span>
                                                <?= $escaper->escapeHtml(__('Shipping Address')) ?>
                                            </span>
                                        </strong>
                                        <div class="box-content">
                                            <address><?= /* @noEscape */ $block->getFormattedAddress($order
                                            ->getShippingAddress()); ?></address>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <div class="block block-order-details-view">
                    <div class="block-title">
                        <strong><?= $escaper->escapeHtml(__('Payment & Shipping Method')) ?></strong>
                    </div>
                    <div class="block-content">
                        <div class="box box-order-billing-method wk-box">
                            <strong class="box-title">
                                <span><?= $escaper->escapeHtml(__('Payment Information')) ?></span>
                            </strong>
                            <div class="box-content">
                                <?= $escaper->escapeHtml($payment_method); ?>
                            </div>
                        </div>
                        <?php if ($block->isOrderCanShip($order)): ?>
                            <div class="box box-order-shipping-method wk-box">
                                <strong class="box-title">
                                    <span><?= $escaper->escapeHtml(__('Shipping and Tracking Information')) ?></span>
                                </strong>
                                <div class="box-content">
                                    <?php if ($order->getShippingDescription()): ?>
                                        <?= $escaper->escapeHtml($order->getShippingDescription()) ?>
                                    <?php else: ?>
                                        <?= $escaper->escapeHtml(__('No shipping information available')); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="block block-order-details-view wk-order-title-block">
                    <div class="block-title">
                        <strong><?= $escaper->escapeHtml(__('Items Refunded')) ?></strong>
                    </div>
                </div>
                <div class="order-details-items ordered">
                    <div class="order-title">
                        <strong><?= $escaper->escapeHtml(__('Items Refunded')) ?></strong>
                    </div>
                    <?= $block->getChildHtml('marketplace_order_creditmemo_items') ?>
                </div>
            </div>
        </div>
        <div class="buttons-set">
            <p class="back-link">
                <a href="<?= $escaper->escapeUrl($block->getUrl('marketplace/order/history', ['_secure' => $block
                ->getRequest()->isSecure()]));?>" class="left">&laquo;
                <?= $escaper->escapeHtml(__('Back To My Orders')) ?>
            </a>
            </p>
        </div>
        <?php
    }
} else { ?>
    <h2 class="wk-mp-error_msg">
        <?= $escaper->escapeHtml(__("To Become Seller Please Contact to Admin.")); ?>
    </h2>
    <?php
} ?>
