<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
$item = $block->getParentBlock()->getItem();
$profileModel = $block->getProfileHelper();
$product = $item->getProduct();
if ($product && ($productId = $product->getId())) {
    $sellerId = $profileModel->getUserInfo($productId, $item->getOrderId());
    if ($sellerId) {
        list($shopTitle, $shopUrl) = $profileModel->getSellerDetails($sellerId);
        ?>
        <div class="wk-seller-block wk-block" id="mp-wk-block">
            <div>
                <span class="wk-block-font-bold-up"><?= $escaper->escapeHtml(__('Sold By'))?></span>
                <span class="wk-block-title-css">
                    <a href="<?= $escaper->escapeUrl($profileModel->getShopUrl($shopUrl));?>" 
                    title="<?= $escaper->escapeHtml(__('Visit Shop')) ?>" 
                    id="profileconnect"><?= $escaper->escapeHtml($shopTitle); ?></a>
                </span>
            </div>
        </div>
        <?php
    }
} ?>
