<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<img
    src="<?= $escaper->escapeUrl($block->getSellerStatisticsGraphUrl('feed_quality')) ?>"
    alt="<?= $escaper->escapeHtml(__('Quality Reviews'))?>"
    title="<?= $escaper->escapeHtml(__('Quality Reviews'))?>" />
