<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$currentUrl = $escaper->escapeUrl($block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]));
$helper = $viewModel->getHelper();
$partner=$block->getProfileDetail();
if (!empty($partner['shop_url'])) {
    $sellerId =  $partner->getSellerId();
    $feeds = $helper->getFeedTotal($sellerId);
    $widthQualityStar5 = $widthQualityStar4 = $widthQualityStar3 = $widthQualityStar2 = $widthQualityStar1 = 0;
    
    $borderQualityStar5 = $borderQualityStar4 = $borderQualityStar3 = $borderQualityStar2 = $borderQualityStar1 = 0;

    if ($feeds['feedcount']) {
        $widthQualityStar5 = (($feeds['quality_star_5']+$feeds['price_star_5']+$feeds['value_star_5'])*100)
                            /($feeds['feedcount']*3);
        if ($widthQualityStar5) {
            $borderQualityStar5 = 3;
        }
        $widthQualityStar4 = (($feeds['quality_star_4']+$feeds['price_star_4']+$feeds['value_star_4'])*100)
        /($feeds['feedcount']*3);
        if ($widthQualityStar4) {
            $borderQualityStar4 = 3;
        }
        $widthQualityStar3 = (($feeds['quality_star_3']+$feeds['price_star_3']+$feeds['value_star_3'])*100)
        /($feeds['feedcount']*3);
        if ($widthQualityStar3) {
            $borderQualityStar3 = 3;
        }
        $widthQualityStar2 = (($feeds['quality_star_2']+$feeds['price_star_2']+$feeds['value_star_2'])*100)
        /($feeds['feedcount']*3);
        if ($widthQualityStar2) {
            $borderQualityStar2 = 3;
        }
        $widthQualityStar1 = (($feeds['quality_star_1']+$feeds['price_star_1']+$feeds['value_star_1'])*100)
        /($feeds['feedcount']*3);
        if ($widthQualityStar1) {
            $borderQualityStar1 = 3;
        }
    }
    $avgPriceRatingStar = round(($feeds['price']/20), 1, PHP_ROUND_HALF_UP);
    
    $avgValueRatingStar = round(($feeds['value']/20), 1, PHP_ROUND_HALF_UP);
    
    $avgQualityRatingStar = round(($feeds['quality']/20), 1, PHP_ROUND_HALF_UP);
    
    ?>
    <div class="wk-seller-rating-contaainer">
        <div class="wk-seller-rating-left-container">
           <div class="wk-rating-left-block">
                <div class="rating-section">
                    <?= $escaper->escapeHtml($helper->getSelleRating($sellerId)); ?>
                </div>
                <span class='rating-line'>
                    <?= $escaper->escapeHtml(__('Rating based on'))?>
                </span>
                <div class="wk-review-count"> 
                    <div class="wk-mp-count-txt rating-count">
                        
                        <?php $sellerId =  $partner->getSellerId();
                            $feedTotal  = $helper->getFeedTotal($sellerId);
                        ?>
                        <?= $escaper->escapeHtml($feedTotal['feedcount'])?>
                    </div>
                    <div class="wk-mp-collection-header-bottom">
                        <?= $escaper->escapeHtml(__('Reviews'))?>
                    </div>
                </div>
                <button class="write-review">
                    <a href="#">
                        <?= $escaper->escapeHtml(__('Write Your Reviews'))?>
                    </a>
                </button>
                <div class="wk-mp-rating-individual">
                
                    <div class="wk-mp-rating-individual-right">
                        <div  class="wk-mp-rating-progress-bar-container">
                            <div class="wk-mp-rating-individual-right-txt">
                                <?= $escaper->escapeHtml(__('5 Star '))?>
                            </div>
                            <div class="wk-mp-rating-individual-progress-bar">
                                <small>
                                    <span class="wk-mp-rating-progress-color-bar wk-mp-star5-rating-color-bar"
                                    style="width:<?= $escaper->escapeHtml($widthQualityStar5); ?>%; 
                                    border-width:<?= $escaper->escapeHtml($borderQualityStar5); ?>px;"></span>
                                </small>
                            </div>
                            <div class="wk-mp-rating-individual-txt">
                                <?= $escaper->escapeHtml(__(' (%1)', ($feeds['quality_star_5']
                                +$feeds['price_star_5']+$feeds['value_star_5'])))?>
                            </div>
                        </div>
                        <div class="wk-mp-rating-progress-bar-container">
                            <div class="wk-mp-rating-individual-right-txt">
                                <?= $escaper->escapeHtml(__('4 Star '))?>
                            </div>
                            <div class="wk-mp-rating-individual-progress-bar">
                                <small>
                                    <span class="wk-mp-rating-progress-color-bar wk-mp-star4-rating-color-bar" 
                                    style="width:<?= $escaper->escapeHtml($widthQualityStar4); ?>%; 
                                    border-width:<?= $escaper->escapeHtml($borderQualityStar4); ?>px;"></span>
                                </small>
                            </div>
                            <div class="wk-mp-rating-individual-txt">
                                <?= $escaper->escapeHtml(__(' (%1)', ($feeds['quality_star_4']+
                                $feeds['price_star_4']+$feeds['value_star_4'])))?>
                            </div>
                        </div>
                        <div  class="wk-mp-rating-progress-bar-container">
                            <div class="wk-mp-rating-individual-right-txt">
                                <?= $escaper->escapeHtml(__('3 Star '))?>
                            </div>
                            <div class="wk-mp-rating-individual-progress-bar">
                                <small>
                                    <span class="wk-mp-rating-progress-color-bar wk-mp-star3-rating-color-bar" 
                                    style="width:<?= $escaper->escapeHtml($widthQualityStar3); ?>%; 
                                    border-width:<?= $escaper->escapeHtml($borderQualityStar3); ?>px;"></span>
                                </small>
                            </div>
                            <div class="wk-mp-rating-individual-txt">
                                <?= $escaper->escapeHtml(__(' (%1)', ($feeds['quality_star_3']+
                                $feeds['price_star_3']+$feeds['value_star_3'])))?>
                            </div>
                        </div>
                        <div class="wk-mp-rating-progress-bar-container">
                            <div class="wk-mp-rating-individual-right-txt">
                                <?= $escaper->escapeHtml(__('2 Star '))?>
                            </div>
                            <div class="wk-mp-rating-individual-progress-bar">
                                <small>
                                    <span class="wk-mp-rating-progress-color-bar wk-mp-star2-rating-color-bar"
                                    style="width:<?= $escaper->escapeHtml($widthQualityStar2); ?>%; 
                                    border-width:<?= $escaper->escapeHtml($borderQualityStar2); ?>px;"></span>
                                </small>
                            </div>
                            <div class="wk-mp-rating-individual-txt">
                                <?= $escaper->escapeHtml(__(' (%1)', ($feeds['quality_star_2']
                                +$feeds['price_star_2']+$feeds['value_star_2'])))?>
                            </div>
                        </div>
                        <div class="wk-mp-rating-progress-bar-container">
                            <div class="wk-mp-rating-individual-right-txt">
                                <?= $escaper->escapeHtml(__('1 Star '))?>
                            </div>
                            <div class="wk-mp-rating-individual-progress-bar">
                                <small>
                                    <span class="wk-mp-rating-progress-color-bar wk-mp-star1-rating-color-bar"
                                    style="width:<?= $escaper->escapeHtml($widthQualityStar1); ?>%; 
                                    border-width:<?= $escaper->escapeHtml($borderQualityStar1); ?>px;"></span>
                                </small>
                            </div>
                            <div class="wk-mp-rating-individual-txt">
                                <?= $escaper->escapeHtml(__(' (%1)', ($feeds['quality_star_1']+
                                $feeds['price_star_1']+$feeds['value_star_1'])))?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="average-star-ratings-block">
                    <div class="wk-rating-blocks">
                        <div class="average-rating quality">
                            <div class="rating-star quantity"><?= $escaper->escapeHtml($avgQualityRatingStar)?></div>
                        </div>
                        <div class ="avg-rating-contetn quality">
                            <span class="heading"><?= $escaper->escapeHtml(__('Average Quality'))?></span>
                            <span class="total-reviewc-count">
                                <?= $escaper->escapeHtml($feeds['feedcount'].__(' Ratings'))?>
                            </span>
                        </div>
                    </div>
                    <div class="wk-rating-blocks">
                        <div class="average-rating price">
                            <div class="rating-star price"><?= $escaper->escapeHtml($avgPriceRatingStar)?></div>
                        </div>
                        <div class ="avg-rating-contetn price">
                            <span class="heading"><?= $escaper->escapeHtml(__('Average Price'))?></span>
                            <span class="total-reviewc-count">
                                <?= $escaper->escapeHtml($feeds['feedcount'].__(' Ratings'))?>
                            </span>
                        </div>
                    </div>
                    <div class="wk-rating-blocks">
                        <div class="average-rating value">
                            <div class="rating-star value"><?= $escaper->escapeHtml($avgValueRatingStar)?></div>
                        </div>
                        <div class ="avg-rating-contetn quality">
                            <span class="heading"><?= $escaper->escapeHtml(__('Average Value'))?></span>
                            <span class="total-reviewc-count">
                                <?= $escaper->escapeHtml($feeds['feedcount'].__(' Ratings'))?>
                            </span>
                        </div>
                    </div>
                   
                </div>
           </div>
        </div>
        <div class="wk-seller-rating-right-container">
            <?php
            foreach ($block->getFeedCollection() as $keyed) {
                $feedcustomer = $block->getCustomer($keyed['buyer_id']);
                $name = $keyed['feed_nickname'];
                $feedDateTime= strtotime($keyed['created_at']);
                $feedDate = date('M d, Y', $feedDateTime);
                $feedPrice = round(($keyed['feed_price']/20), 1, PHP_ROUND_HALF_UP);
                $feedValue = round(($keyed['feed_value']/20), 1, PHP_ROUND_HALF_UP);
                $feedQuality = round(($keyed['feed_quality']/20), 1, PHP_ROUND_HALF_UP);
                ?>
                <div class="wk-mp-rating-row">
                    <div class="wk-mp-customer-row">
                        <span class="wk-mp-rating-customer-name">
                            <?= $escaper->escapeHtml($name)?>
                        </span>
                    </div>
                    <span class="wk-mp-rating-val-txt wk-mp-float-left">
                            <?= $escaper->escapeHtml($keyed['feed_summary'])?>
                    </span>
                    <div class="wk-mp-rating-summary-container">
                        
                        <p><?= $escaper->escapeHtml($keyed['feed_review'])?></p>
                    </div>
                    <div class="wk-mp-rating-review-row">
                    
                    <span class="wk-mp-rating-val">
                        <span class="wk-mp-rating-val-txt">
                            <?= $escaper->escapeHtml(__("Pricing")); ?>
                        </span>
                        <span class="wk-mp-rating-icon wk-mp-star">
                            <?= $escaper->escapeHtml($feedPrice)?>
                        </span>
                    </span>
                    <span class="wk-mp-rating-val">
                        <span class="wk-mp-rating-val-txt">
                            <?= $escaper->escapeHtml(__("Value")); ?>
                        </span>
                        <span class="wk-mp-rating-icon wk-mp-star">
                            <?= $escaper->escapeHtml($feedValue)?>
                        </span>
                    </span>
                    <span class="wk-mp-rating-val">
                        <span class="wk-mp-rating-val-txt">
                            <?= $escaper->escapeHtml(__("Quality")); ?>
                        </span>
                        <span class="wk-mp-rating-icon wk-mp-star">
                            <?= $escaper->escapeHtml($feedQuality)?>
                        </span>
                    </span>
                </div>
                <i class="feed-date"><?= $escaper->escapeHtml($feedDate)?></i>
                </div>
                
                <?php
            } ?>
        </div>
    </div>
    <div id="customer-reviews" class="box-collateral box-reviews">
            <div class="form-add">
                <?php
                $flag = 0;
                if ($helper->isCustomerLoggedIn()) {
                    if ($helper->getCustomer()->getId() != $sellerId) { ?>
                        <?php
                        $flag = 2;
                        $feedavailflag = 0;
                        $ordercount = 0;
                        $feedbackcount = 0;
                        if ($helper->getReviewStatus()) {
                            $flag = 1;
                            $collectionfeed=$block->getFeedcountCollection();
                            foreach ($collectionfeed as $value) {
                                $ordercount = $value->getOrderCount();
                                $feedbackcount = $value->getFeedbackCount();
                            }
                            if ($feedbackcount<$ordercount) {
                                $feedavailflag =1;
                            }
                        }
                        if (($flag==2) || ($flag==1 && $feedavailflag ==1)) { ?>
                            <div class="showreview">
                                <div class="wk-mp-design">
                                    <div><h3><strong><?= $escaper->escapeHtml(__('Write Your Feedback')) ?>
                                </strong></h3></div>
                                    <div class="fieldset wk-mp-fieldset">
                                        <form id="review-form" method="post" action="<?= $escaper
                                        ->escapeUrl($block->getUrl('marketplace/seller/newfeedback', ['_secure' =>
                                        $block->getRequest()->isSecure()])) ?>" enctype="multipart/form-data" >
                                            <?= $block->getBlockHtml('formkey'); ?>
                                            <fieldset class="fieldset info wk-mp-fieldset">
                                                <h3><?= $escaper->escapeHtml(__('How do you rate this Store')) ?>?</h3>
                                                <span id="input-message-box"></span>
                                                <table id="product-review-table" class="data-table">
                                                <colgroup>
                                                    <col>
                                                    <col width="1">
                                                    <col width="1">
                                                    <col width="1">
                                                    <col width="1">
                                                    <col width="1">
                                                </colgroup>
                                                <thead>
                                                    <tr class="first last">
                                                        <th>&nbsp;</th>
                                                        <th><span class="nobr">1 
                                                            <?= $escaper->escapeHtml(__('star')) ?></span></th>
                                                        <th><span class="nobr">2 
                                                            <?= $escaper->escapeHtml(__('stars')) ?></span></th>
                                                        <th><span class="nobr">3 
                                                            <?= $escaper->escapeHtml(__('stars')) ?></span></th>
                                                        <th><span class="nobr">4 
                                                            <?= $escaper->escapeHtml(__('stars')) ?></span></th>
                                                        <th><span class="nobr">5 
                                                            <?= $escaper->escapeHtml(__('stars')) ?></span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr class="first odd">
                                                        <th><?= $escaper->escapeHtml(__('Price')) ?></th>
                                                        <td class="value"><input type="radio" class="radio" 
                                                        value="20" id="Price_1" name="feed_price" checked="checked"/>
                                                        </td>
                                                        <td class="value"><input type="radio" class="radio" value="40" 
                                                        id="Price_2" name="feed_price"></td>
                                                        <td class="value"><input type="radio" class="radio" value="60" 
                                                        id="Price_3" name="feed_price"></td>
                                                        <td class="value"><input type="radio" class="radio" value="80" 
                                                        id="Price_4" name="feed_price"></td>
                                                        <td class="value last"><input type="radio" class="radio" 
                                                        value="100" 
                                                        id="Price_5" name="feed_price"></td>
                                                    </tr>
                                                    <tr class="even">
                                                        <th><?= $escaper->escapeHtml(__('Value')) ?></th>
                                                        <td class="value"><input type="radio" class="radio" value="20" 
                                                        id="Value_1" name="feed_value" checked="checked"/></td>
                                                        <td class="value"><input type="radio" class="radio" value="40" 
                                                        id="Value_2" name="feed_value"></td>
                                                        <td class="value"><input type="radio" class="radio" value="60"
                                                         id="Value_3" name="feed_value"></td>
                                                        <td class="value"><input type="radio" class="radio" value="80" 
                                                        id="Value_4" name="feed_value"></td>
                                                        <td class="value last"><input type="radio" class="radio" 
                                                        value="100" id="Value_5" name="feed_value"></td>
                                                    </tr>
                                                    <tr class="last odd">
                                                        <th><?= $escaper->escapeHtml(__('Quality')) ?></th>
                                                        <td class="value"><input type="radio" class="radio" value="20" 
                                                        id="Quality_1" name="feed_quality" checked="checked"/></td>
                                                        <td class="value"><input type="radio" class="radio" value="40" 
                                                        id="Quality_2" name="feed_quality"></td>
                                                        <td class="value"><input type="radio" class="radio" value="60" 
                                                        id="Quality_3" name="feed_quality"></td>
                                                        <td class="value"><input type="radio" class="radio" value="80" 
                                                        id="Quality_4" name="feed_quality"></td>
                                                        <td class="value last"><input type="radio" class="radio" 
                                                        value="100" id="Quality_5" name="feed_quality"></td>
                                                    </tr>
                                                </tbody>
                                                </table>
                                                <input type="hidden" name="seller_id" id="seller_id" value="<?=
                                                $escaper->escapeHtml($partner->getSellerId()); ?>"/>
                                                <input type="hidden" name="shop_url" value="<?=
                                                $escaper->escapeUrl($partner->getShopUrl()); ?>" />
                                                <div class="field required">
                                                    <label class="label"><?= $escaper->escapeHtml(__('Nickname')) ?>
                                                    </label>
                                                    <div class="control">
                                                        <input type="text" value="<?=
                                                        $escaper->escapeHtml($block->getCustomerSessionName()); ?>"
                                                        class="input-text required-entry widthinput nickname" 
                                                        id="nickname_field"
                                                        name="feed_nickname">
                                                    </div>
                                                </div>
                                                <div class="field required">
                                                    <label class="label">
                                                        <?= $escaper->escapeHtml(__('Summary of Your Review')) ?>
                                                    </label>
                                                    <div class="control">
                                                        <input type="text" value="" 
                                                        class="input-text required-entry widthinput summary_field" 
                                                        id="summary_field" name="feed_summary">
                                                    </div>
                                                </div>
                                                <div class="field required">
                                                    <label class="label"><?= $escaper->escapeHtml(__('Review')) ?>
                                                </label>
                                                    <div class="control">
                                                        <textarea class="required-entry widthinput review_field" 
                                                        rows="3" cols="5" id="review_field"
                                                         name="feed_review"></textarea>
                                                    </div>
                                                </div>
                                            </fieldset>
                                            <div class="buttons-set">
                                                <button class="button"
                                                title="<?= $escaper->escapeHtml(__('Submit Review')) ?>" 
                                                type="submit"><span><span>
                                                    <?= $escaper->escapeHtml(__('Submit Review')) ?>
                                                </span></span></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <?php
                        } else { ?>
                            <div class="showreview"><p class="note-msg"><?=
                            $escaper->escapeHtml(__('You need to purchase item(s) first to make a review.'))
                            ?></p></div>
                            <?php
                        }
                    } else { ?>
                        <center>
                        <p class="loginmsg">
                            <a class="button-large" 
                                href="<?=
                                        $escaper->escapeUrl(
                                            $block->getUrl(
                                                'marketplace/seller/feedback/',
                                                [
                                                    '_secure' => $block->getRequest()->isSecure(),
                                                    'referer' => base64_encode($currentUrl)
                                                ]
                                            )
                                        )
                                        ?>">
                                <button class="button-large">
                                    <span>
                                        <?= $escaper->escapeHtml(__('All Reviews')) ?>
                                    </span>
                                </button>
                            </a>
                            <?=
                                $escaper->escapeHtml(
                                    __('You cannot add review for your own shop.')
                                )
                            ?>
                        </p>
                        </center>
                        <?php
                    }
                } else { ?>
                    <?php $block->setCustomerSessionAfterAuthUrl();?>
                    <center>
                        <p class="loginmsg">
                            <a class="button-large" 
                                href="<?=
                                        $escaper->escapeUrl(
                                            $block->getUrl(
                                                'marketplace/seller/feedback/',
                                                [
                                                    '_secure' => $block->getRequest()->isSecure(),
                                                    'referer' => base64_encode($currentUrl)
                                                ]
                                            )
                                        )
                                        ?>">
                                <button class="button-large">
                                    <span>
                                        <?= $escaper->escapeHtml(__('All Reviews')) ?>
                                    </span>
                                </button>
                            </a>
                            <a class="button-large" 
                                href="<?=
                                        $escaper->escapeUrl(
                                            $block->getUrl(
                                                'customer/account/login/',
                                                [
                                                    '_secure' => $block->getRequest()->isSecure(),
                                                    'referer' => base64_encode($currentUrl)
                                                ]
                                            )
                                        ) ?>">
                                <button class="button-large">
                                    <span>
                                        <?= $escaper->escapeHtml(__('Login To Give Feedback')) ?>
                                    </span>
                                </button>
                            </a>
                        </p>
                    </center>
                    <?php
                } ?>
            </div>
        </div>
<?php } ?>
